### ISSUE TITLE
Polling and feature_flag_called event spam

### ISSUE THREAD

**Issue by razor-x** [PostHog/posthog-js#100]
If I update a feature flag, I want my UI to update quickly once the flag is changed. For context, this is a react app. To do this, I

1. Set a global interval on my app to call `reloadFeatureFlags` every minute. This lets me control how many network calls will happen and how often I will check for flag updates.
2. Have a react hook that returns the value of a feature flag. The hooks sets an interval to call `isFeatureEnabled` every second.

This works well because I do not need to coordinate `reloadFeatureFlags` and `isFeatureEnabled`. One handles the network updates, the other the UI refresh rate and a change is reflected in at most 61 seconds. 

This was working fine since there is no network call for `isFeatureEnabled` (just the local cache lookup). However the addition of `$feature_flag_called` generated 1 event per second event spam. I was forced to increase the interval to 2 minutes. But this is not ideal since now it delays flag updates by up to 3 minutes and still generates these extra events.

https://github.com/PostHog/posthog-js/blob/c700c1b27758b0826aa93af3b3d3e6c75f826a2b/src/posthog-featureflags.js#L61

Anyway, just wanted to give this feedback, and possibly recommend allowing the user to disable  `$feature_flag_called`  and / or if you have a better system to manage timely flag updates for react, updating the docs with a recommend hooks pattern.

**Comment by timgl** [comment]
Hey @razor-x, thanks for giving us this feedback, and it's a great point. For now, I'd suggest doing the following instead of isFeatureEnabled:
`posthog.featureFlags.getFlags().indexOf("feature flag key") > -1`

This won't send the event. Meanwhile I'll have a think about creating a better API for this.

Thanks!
Tim

**Comment by razor-x** [comment]
Heads up, since featureFlags does not exist until after init, it has to be

```
posthog.featureFlags ? posthog.featureFlags.getFlags().indexOf("feature flag key") > -1 : false
```

**Comment by razor-x** [comment]
Just reporting that I have to disable the use of this feature on my app until this issue is addressed. The client does not actually have a `featureFlags` method that one can access (see below). Our team really loves PostHog but I have to express my frustration as an engineer at this update in the hope that future updates will better consider potential impact. I understand these mistake happen, I have certainly made worse.

To summarize a postmortem on our side, this change has so far resulted in

1. Unexpectedly consuming our account's event limit.
2. A fatal error for our users on deploying the suggested hotfix.
3. A non-trival amount of unplanned work dealing with the impact of this issue.
4. Now having to disable feature flags and thus user features until I have a safe next step.  

Options I am considering to move forward

1. Rolling back the posthog-js version (unsure if this will have issues with the recent PostHog update).
2. Creating a new project for our staging env so updates like this can be better tested (only recently noticed this feature added to the UI).

PostHog is one of the few (possibly only) things that is unique to our production environment since it does not provide a way to test it without polluting production data. In hindsight, with this knowledge, more care on our end should have been taken before rolling out any updates to the PostHog client. I recommend other do the same.

Best.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/721372/96955453-754e6580-14aa-11eb-9138-225e3ff28092.png">

**Comment by macobo** [comment]
Thanks for sharing the feedback @razor-x, definitely super valuable and sorry for the pain this managed to cause.

I've opened two issues/feature ideas regarding this in the main repo. Let us know if you have context/ideas or feedback on those.

Would you be up for scheduling a call with us as well, to gather some live feedback and dig in a bit more? https://calendly.com/posthog-feedback

**Comment by weyert** [comment]
Yes, it's all a bit hackery if you ask me, if you want to use this library in something like React and/or Next.js. I am really interested in the `posthog-lite-js`-project.
