### ISSUE TITLE
Bot traffic (Ahrefs crawler) not filtered out

### ISSUE THREAD

**Issue by MiKatre** [PostHog/posthog-js#1010]
Hi, I noticed a huge spike in views recorded by PostHog. After some digging I found it was the Ahrefs crawler crawling my website:

User agent `AhrefsSiteAudit (Desktop) - Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/)`

I open an issue because according to [this question](https://posthog.com/questions/for-session-replays-are-you-able-to-filter-out-specific-sessions), this is where we should report missing bots.

Thanks!

**Comment by pauldambra** [comment]
Hi @MiKatre,

I added a test to check that user agent string and it should have been considered a bot. You can see in the first commit here https://github.com/PostHog/posthog-js/pull/1011

Can you share what version of posthog-js you're using and ho wyou had it configured? 

Thanks

**Comment by pauldambra** [comment]
I'll close this but feel free to re-open it if this is still a problem for you and you can share the details above

**Comment by MiKatre** [comment]
Thanks ! 
I just tried to enable PostHog **User Agent Populator** to make sure I gave you the correct user agent, and run a crawl with the **Ahref Site Audit Tool**, but the bot traffic was successfully filtered out, so I don't know what happened last time.

On the other hand, by doing that I found a bot that I am sure this time is not listed in `blocked-uas.ts`! :

https://github.com/PostHog/posthog-js/issues/1112
