### ISSUE TITLE
`$set` properties not getting sent in `captureEvent`

### ISSUE THREAD

**Issue by aseemk** [PostHog/posthog-js#1019]
Hi there! I'm new to PostHog and generally loving it so far — thank you. =)

I'm seeing some surprising behavior which _seems_ like a bug. But this _was_ working earlier last week, so it's very possible I've caused a regression on my end — but I didn't change anything here, and the code looks so simple, so I'm not sure.

I'm capturing an event like this:

```ts
  posthog.capture(name, props, {
    $set: user,
  })
```

And logging a line immediately above this confirming the values of the variables are set as I think they are:

```ts
  console.log('calling `posthog.capture` with:', {
    name,
    props,
    options: {
      $set: user,
    },
  })
```

My log prints correctly:

<p><img src="https://github.com/PostHog/posthog-js/assets/537838/88db2856-0e26-41c9-9e25-44540b59f0e7" width=499 /></p>

**You can see I'm passing custom properties to `$set` on the person, like `name` and `gender`.**

**I'm unfortunately not seeing these properties get set on the person in PostHog, or passed through in `$set` on this event:**

<p><img src="https://github.com/PostHog/posthog-js/assets/537838/84f0f2c6-f229-411b-86d7-a4482d230794" width=833 /></p>

**And when I enable `posthog.debug(true)` on my posthog-js instance, I similarly don't see any `$set` passed with the event:**

![Screenshot 2024-02-12 at 9 29 36 AM](https://github.com/PostHog/posthog-js/assets/537838/d84a9874-27d0-4205-a27d-597a8496695a)

(I also don't see any other debug lines printed for other sends immediately after this, e.g. `identify`. And to be clear, we _are_ calling `posthog.identify()` before this, on initial page load, and I do see `$set` being included there.)

Am I doing something wrong here, or misunderstanding the API?

I'll try calling an explicit separate `setPersonProperties` instead for now, but wanted to file this bug in the meantime. Thank you!

**Comment by pauldambra** [comment]
you can see the code here that takes $set from options onto the props here https://github.com/PostHog/posthog-js/blob/main/src/posthog-core.ts#L804-L807

is this still happening for you? i'll close it since the amount of time has passed (sorry you had no response) feel free to reopen if it's still happening
