### ISSUE TITLE
Posthog Queue not working in Brave Browser

### ISSUE THREAD

**Issue by gajraj-gan** [PostHog/posthog-js#1021]
Hi,

I am new to posthog. We have recently add posthog in our React App. However it is not working on brave browser. 
In rest of browser, the "polling" function of posthog-js works, and sends the events periodically but it doesnt work in the brave brower. The Queue keeps getting filled up.

I have verified this by using the devtools of the Brave Browser.
Any idea on how to fix this?

<img width="420" alt="Screenshot 2024-02-13 at 9 44 57 PM" src="https://github.com/PostHog/posthog-js/assets/140384335/028139ea-e4b4-467d-afa0-fd0fefd5d815">

**Comment by pauldambra** [comment]
hey @gajraj-gan, I expect this to be brave blocking tracking scripts - this is one of the reasons people use brave https://brave.com/shields/

You can switch the tracking blocking off in brave, you can turn off tracking by clicking the brave shield in the browser
