### ISSUE TITLE
Loading toolbar programatically fails for EU dashboard

### ISSUE THREAD

**Issue by MathiasWP** [PostHog/posthog-js#1041]
I'm programatically loading the toolbar via the `loadToolbar` API.

When i want to authenticate the toolbar, i get redirected to `https://eu.i.posthog.com/authorize_and_redirect/?redirect=http%3A%2F%2Flocalhost%3A5173%2F`, which is an invalid website. I have not changed any the values in our `ToolbarParamsEU` object.

https://github.com/PostHog/posthog-js/assets/48158184/862e6b9c-9e5b-4bd2-a30d-9870b71a0660

**Comment by benjackwhite** [comment]
Oooh thanks for the report! This looks like an edge case that might have got missed as we started setting up our dedicated ingestion endpoints. I'll get a fix up ASAP.

**Comment by benjackwhite** [comment]
Fix coming up https://github.com/PostHog/posthog-js/pull/1042/files
