### ISSUE TITLE
Authorising with toolbar does not work when loaded via code

### ISSUE THREAD

**Issue by MathiasWP** [PostHog/posthog-js#1067]
For a couple of weeks now we've had this issue:

https://github.com/PostHog/posthog-js/assets/48158184/13a89018-353b-4c87-a11d-6ee5c9f8ef2c

We are unable to authorise the PostHog toolbar which we've loaded programatically:

```ts
import { PUBLIC_POSTHOG_EU_HOST, PUBLIC_POSTHOG_PROJECT_API_KEY } from '$env/static/public';
import posthog, { type ToolbarParams } from 'posthog-js';

/**
 * The ToolbarParams type does not have apiURL and jsURL defined,
 * but they're required to load the EU version of the PostHog toolbar
 */
type ToolbarParamsEU = ToolbarParams & { apiURL: string; jsURL: string };

const toolbarParams: ToolbarParamsEU = {
	apiURL: PUBLIC_POSTHOG_EU_HOST,
	dataAttributes: ['data-attr'],
	instrument: true,
	jsURL: 'https://app-static.eu.posthog.com',
	token: PUBLIC_POSTHOG_PROJECT_API_KEY,
	toolbarVersion: 'toolbar'
	/**
	 * These keys are provided by PostHog when enabling
	 * the tooolbar from the PostHog dashboard, but
	 * it does not seem like they're required for the toolbar to work.
	 */
	// temporaryToken: '<token>',
	// userEmail: '<name>@kvistsolutions.com'
	// distinctId: '<id>'
};

export function loadPostHogToolbar() {
	posthog.loadToolbar(toolbarParams);
}

```

**Comment by benjackwhite** [comment]
The toolbar depends on a # param being available when it loads. This can get stuck with some routers if the router replaces that value _before_ the JS is ready.

Could you open an in app support ticket with a link to the website so we can test it ourselves and validate if this is the case?

**Comment by benjackwhite** [comment]
Also - Not sure why you are loading it that way. You should just be able to call `posthog.loadToolbar()` and it will use the appropriate config from the standard JS config. Is there a specific reason you are doing it this way?

**Comment by MathiasWP** [comment]
> Also - Not sure why you are loading it that way. You should just be able to call `posthog.loadToolbar()` and it will use the appropriate config from the standard JS config. Is there a specific reason you are doing it this way?

I'm doing it this way because i want the Toolbar to be automatically loaded every time we go into a preview or staging environment without having to go through the PostHog dashboard. We _always_ want our feature flags available, so going through the PostHog dashboard is just a time consuming step for us.

I checked how the # param looked like when loading the PostHog toolbar, and it returned basically the config i've set up in the code above. This worked for a long time, but it stopped working about 3 weeks ago.

**Comment by MathiasWP** [comment]
Is this not supposed to be a valid way of doing this @benjackwhite?
