### ISSUE TITLE
Feature flags do not work after upgrading to 1.116.2

### ISSUE THREAD

**Issue by Garmien** [PostHog/posthog-js#1090]
We upgraded from 1.106.3 to 1.116.2, and had to roll back immediately because feature flags stopped working. Everything else (autocapture etc) seemed to work fine.

**Comment by neilkakkar** [comment]
Hey Garmien, do you have any more information? What environment is this in, and can I see a code snippet? And do you see any error in the console log? Maybe something like this? -> https://github.com/PostHog/posthog-js/issues/1079

**Comment by Garmien** [comment]
We were a bit puzzled on this one, since it worked locally but not in production. But we found out that the posthog.init function no longer returnes the PostHog instance itself. Instead we are supposed to use the default import from the library now. We're wondering why this hasn't been marked as a breaking change, as it does in fact break things potentially.

However we have fixed it now and it is working again.

**Comment by benjackwhite** [comment]
`posthog-js` does return the instance when calling init. The only case where it doesn't is if you don't pass a project api key or if the JS was already initialized.

I'm going to assume this case might be the second one. That is indeed a regression which we can get patched up
