### ISSUE TITLE
Version 1.6.0 broke server-side rendering

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog-js#114]
User @weyert reported in slack:

> Anyone know why these lines 4-22 got deleted in 1.6.0 of posthog-js? https://github.com/PostHog/posthog-js/compare/v1.5.2...v1.6.0#diff-3274f1a37032fb0ae4e2823def0007c634e869ae0dfc304ff6a12c36513c3a52L4 (edited) 
> this change makes is harder to use posthog-js with server-side rendering React e.g. Next.js

The change in question removed some appearing-to-be unneeded test scaffolding code which seems to have helped with server-side rendering.

In addition to re-adding the missing pieces back in it would be great to have a sample of this setup to add a test for it to avoid breaking it in the future.

**Comment by macobo** [comment]
From looking at the code, I believe the problematic references are to `window.navigator['sendBeacon']`, `window.location`, and `document.location` which are used in in global consts.

We could make initializing these lazy, not sure how posthog gets initialized though with server-side rendering.

**Comment by macobo** [comment]
@weyert We've released 1.7.0-beta.1 which contains a potential fix - it would be awesome if you could test it out.

**Comment by macobo** [comment]
Ping, @weyert

**Comment by weyert** [comment]
This is working with the recent version v1.80 is working :)
