### ISSUE TITLE
Issue with classifying referring domain after 1.119.2

### ISSUE THREAD

**Issue by benrobertsonio** [PostHog/posthog-js#1159]
After I upgraded my to posthog-js version from 1.117 to 1.128.1, I noticed that insights broke down by referring domain suddenly started being dominated by my domain. 

I grabbed a screenshot as an example:

![CleanShot 2024-05-01 at 11 24 02](https://github.com/PostHog/posthog-js/assets/7781583/c0a4c517-69c6-47ed-ade9-c38f6060b6d7)

You can see here that pageviews from `colorbliss.art` started spiking on the day that I upgraded to `posthog-js@1.128.1`. To test this, I downgraded to `posthog-js@1.119.2` yesterday to see if that would change anything. You can see in the screenshot that `www.google.com` spiked and `colorbliss.art` dropped.

Not sure if others have experienced the same.

This is especially visible on events I capture around purchases, since 95% of those events now have no meaningful referral data.

I haven't yet narrowed down which version of `posthog-js` introduced the error. I've looked through the release log and didn't see anything obvious to me that looked like a fix for it either.

I can keep experimenting with versions, but just wanted to flag in case others are seeing the same.

**Comment by robbie-c** [comment]
Hey @benrobertsonio - could you try a recent version (>=1.149.0)? I believe https://github.com/PostHog/posthog-js/pull/1314 should have fixed this

**Comment by benrobertsonio** [comment]
I've been on 1.148 for a few weeks and it seems much improved. Thanks for following up!

**Comment by robbie-c** [comment]
Great, thanks for letting us know!
