### ISSUE TITLE
useFeatureFlag not updating on component re render.

### ISSUE THREAD

**Issue by sachindabadu-ai** [PostHog/posthog-js#1180]
While trying to implement useFeatureFlag we are facing a issue where even id a component is being re rendered the flag value is not being updated. We do get updated flag when we refresh the page but not on component re render.

Expected Behavior:

The feature flag (activity-filter) should update its value when the component re-renders without requiring a page refresh.

```
 <PostHogProvider apiKey={environment.postHogKey} options={options}>
   <App history={history} dispatch={store.dispatch} />
  </PostHogProvider>
``` 
is wrapping App.jsx.

We have added identify the user in App.jsx

```
  const posthog = usePostHog();

  React.useEffect(() => {
     posthog.identify(userId, { email: userEmail });
  }, [posthog, userId, userEmail]); 
```

Trying to check flag using hook

```  const flagEnabled = useFeatureFlagEnabled('activity-filter'); ```

Versions :
```
"node":"18.15.0",
"react": "18.2.0",
"posthog-js": "^1.131.3",
```

What could be going wrong in this implementation? Our component is properly mounted and unmounted in this scenario.

**Comment by benjackwhite** [comment]
Can you elaborate on what is going wrong? 

The feature flag value only updates if the flag value itself changes via polling or something else that would trigger the feature flag change.
Are you seeing the correct value returned from `/decide` but _not_ seeing the hook update?

**Comment by benjackwhite** [comment]
Again, not sure I fully understand but are you expecting "live updates" when you modify something in the PostHog app? Because that isn't how things work.

The SDK will only call `/decide` (which is the endpoint that returns the feature flags state for the given user) on first page load or whenever something changes about the user, for example after you call identify.

**Comment by neilkakkar** [comment]
Indeed, what Ben says is correct. If you want something like 'live updates', you need to poll (by calling `posthog.reloadFeatureFlags()` on an interval from your client.

Usually, there isn't a good reason to do this. If this is purely for testing, you can use the toolbar, or refresh the page like you're doing.
