### ISSUE TITLE
Observing Fetch Requests to be altered

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [PostHog/posthog-js#1185]
Hi,
I am pending to find a non-production reproduction, but wanted to to ask anyhow. When integrating the script from the posthog cloud hosted versions, some fetch requests seem to become altered, essentially loosing the user provided headers, such as the Accept header.

I am running some AI payloads utilising a lib to handle event streams. https://github.com/Azure/fetch-event-source It might be connected to their implementation.

In any case, mutating the headers objects is probably unattended.

Did anyone else experience a similar problem? Is there a way to disable the client sight code that instruments the HTTP classes?

**Comment by pauldambra** [comment]
Hey @eljefedelrodeodeljefe,

Is the site this occurs on public so we can see what is happening? 

We don't alter the headers just copy them so we can capture them. Although you might have spotted something we've not 😊

There are a lot of folks using our header capture so I'd be surprised if this is a general problem here (and super keen to fix it if there is something naughty going on)

**Comment by pauldambra** [comment]
i'm going to close this, i'm confident we're not altering the headers (of course i'd be happy to be proven wrong and we can fix it if so)
