### ISSUE TITLE
How to prevent PostHog to try to connect to the host in development environment?

### ISSUE THREAD

**Issue by stefanobartoletti** [PostHog/posthog-js#1188]
I have implemented PostHog js client in my Nuxt website by following the official guide here https://posthog.com/docs/libraries/nuxt-js

This is my implementation:

```js
import posthog from 'posthog-js'

export default defineNuxtPlugin(() => {
  const runtimeConfig = useRuntimeConfig()
  const posthogClient = posthog.init(runtimeConfig.public.posthogPublicKey, {
    api_host: runtimeConfig.public.posthogHost || 'https://localhost:3000',
    capture_pageview: false, // we add manual pageview capturing below
    persistence: 'memory',
    loaded: (posthog) => {
      if (import.meta.env.MODE === 'development') {
        posthog.debug()
      }
    },
  })

  // Make sure that pageviews are captured with each route change
  const router = useRouter()
  router.afterEach((to) => {
    nextTick(() => {
      posthog.capture('$pageview', {
        current_url: to.fullPath,
      })
    })
  })

  return {
    provide: {
      posthog: () => posthogClient,
    },
  }
})

```

Besides that, I've also created a Vue composable function to capture custom events in various parts of the site:

```js
export const usePosthogCapture = (name, options) => {
  const { $posthog } = useNuxtApp()
  if ($posthog) {
    const posthog = $posthog()
    const route = useRoute()
    posthog.capture(name, {
      path: route.path,
      ...options,
    })
  }
}

```

Everything is working fine, but when I work in the local development environment, I have my browser's console panel filled with errors, apparently because PostHog is not communicating with the API host:

![Screenshot_20240520_143141](https://github.com/PostHog/posthog-js/assets/36746429/1bc04567-cb3b-4b83-b502-bbc25e91b71e)

This is of course not a problem itself (I do not need or want to track my own activity while developing), but I also need to prevent all these errors to pollute the console panel, as it makes very hard to find other error messages and logs that I need during development.

Is there a way to prevent PostHog to try to communicate with the API host in local development?

**Comment by pauldambra** [comment]
Hey Stefano, 

The normal solution would be to not initialise posthog while developing.

There's not a way to run posthog but not have it send data
