### ISSUE TITLE
Automatically set UTM tags as person properties

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog-js#120]
right now we only set utm tags as event properties but it makes sense to set them as user properties too

**Comment by opethrocks** [comment]
I would like to work on this. I see the posthog-people prototype in posthog-people.js. Where can I get the UTM tags from the request url?

**Comment by macobo** [comment]
Look at `utils.js` and `_.info.campaignParams` :)

**Comment by timgl** [comment]
The trick here is we only want to set this once, so you might need to see if any of those campaignParams are already set in the persistence. If not, you can make a call to set the params on the person

**Comment by opethrocks** [comment]
Looks like it is being set in posthog-persistence.js. 

PostHogPersistence.prototype.update_campaign_params = function () {
    if (!this.campaign_params_saved) {
        this.register_once(_.info.campaignParams())
        this.campaign_params_saved = true
    }
}

**Comment by opethrocks** [comment]
`PostHogPersistence.prototype.update_campaign_params = function () {
    if (!this.campaign_params_saved) {
        this.register_once(_.info.campaignParams())
        this.campaign_params_saved = true
    }
}`

**Comment by opethrocks** [comment]
Could I make a call to PostHogPersistence.prototype.update_campaign_params to set the params on the person?

**Comment by timgl** [comment]
Not sure I understand your question! But you could probably put the logic inside of update_campaign

**Comment by opethrocks** [comment]
`PostHogPersistence.prototype.update_campaign_params = function () {
    if (!this.campaign_params_saved) {
        this.register_once(_.info.campaignParams())
        this.campaign_params_saved = true
        PostHogPeople.prototype.set_once("UTM tags", _.info.campaignParams())
    }
}`

This is what I've done. Not sure if it'll work. I'm currently updating my CLT with a slow connection in order to install yarn for testing. I recently upgraded to MacOS 11.0.1 and I'm getting an error when installing yarn.

**Comment by opethrocks** [comment]
You may want to give the issue to someone else. My pull request failed and I can't seem to get my testing environment set up using the instructions on contributing to posthog.

**Comment by yakkomajuri** [comment]
We did this in the plugin server
