### ISSUE TITLE
TypeError: posthog.setPersonProperties is not a function with JS Snippet

### ISSUE THREAD

**Issue by SergioNR** [PostHog/posthog-js#1211]
Hello,

I'm setting up PostHog via GTM with the web snippet from https://eu.posthog.com/project/19615/settings/project#snippet  but when I call posthog.setPersonProperties via GTM I got the Uncaught TypeError: posthog.setPersonProperties is not a function error 😢

<img width="575" alt="image" src="https://github.com/PostHog/posthog-js/assets/71926587/8f770be6-2e7b-461b-8273-0ba0a56aadf5">

**What im doing / How to reproduce:**

1. Load web snippet (https://eu.posthog.com/project/19615/settings/project#snippet) via Google Tag Manager on "page initialization" (No issues here)
<img width="944" alt="image" src="https://github.com/PostHog/posthog-js/assets/71926587/26c1087f-11a2-4f0f-8d73-6e472084717e">
2. Execute the `posthog.setPersonProperties` function via Google Tag Manager on page initializacion with Tag Sequencing active to only execute AFTER posthog web snippet has ran (here is the issue)
<img width="1362" alt="image" src="https://github.com/PostHog/posthog-js/assets/71926587/f004e96a-9bcd-450a-b51f-a8c07384144c">
3. Check DevTools and find "Uncaught TypeError: posthog.setPersonProperties is not a function" error 

I'm using PostHog cloud with the free plan.

Anything I missed?
Thanks!

PS: Might be related to https://github.com/PostHog/posthog-js/issues/702 where `posthog.setPersonProperties` is not being exposed by the web snippet?

**Comment by SergioNR** [comment]
Fixed - Following indications like #702 , i exposed the function on my own and its working now --> 
<img width="828" alt="image" src="https://github.com/PostHog/posthog-js/assets/71926587/c70d9fb5-23b0-409a-9ab1-12101cea07a2">

**Comment by pauldambra** [comment]
resolved in https://github.com/PostHog/posthog/pull/23662
