### ISSUE TITLE
SyntaxError: Unexpected end of JSON input at loadRemoteConfig

### ISSUE THREAD

**Issue by MathiasWP** [PostHog/posthog-js#1220]
We programatically load the toolbar like this:

```ts
/**
 * PostHog defaults to the standard config if no attributes are defined.
 * @see https://github.com/PostHog/posthog-js/issues/1067#issuecomment-1988489889
 */
posthog.loadToolbar({});
```

After authenticating the following error is thrown in our console:

<img width="1013" alt="image" src="https://github.com/PostHog/posthog-js/assets/48158184/6644236e-5e02-45f8-b921-99f227389d3d">

**Comment by pauldambra** [comment]
hey @MathiasWP that's related to the toolbar's hedgehog mode

can you check for the response to a network call to `/api/users/@me/hedgehog_config`?

**Comment by pauldambra** [comment]
ah, wait... i can see this too 🔍
