### ISSUE TITLE
How to manually record logs with SDK

### ISSUE THREAD

**Issue by nebbles** [PostHog/posthog-js#1226]
We use the `debug` package to be able to selectively filter which logs are sent to the console, to avoid to much information in the console at once. However, this means that PostHog doesn't collect the logs in production, which defaults to not sending logs to the console.

In an alternative product we're currently on (we're trialling PostHog) we were able to fix this by calling methods on the SDK (e.g. log(), debug(), warn(), error()) directly rather than relying on the collection from what is printed to the console. You can see the docs here: https://docs.logrocket.com/reference/console

Is this possible in PostHog? Is this likely to be added?

**Comment by pauldambra** [comment]
currently, we only collect logs into session replay. they're searchable there and are displayed against recordings

if we added a manual log method that was only included in replay would that work for you?

otherwise we did make the beginnings of a logging product at our recent company hackathon https://github.com/PostHog/posthog/pull/22289 and we're trying to decide if we should carry on investing in it

**Comment by nebbles** [comment]
> if we added a manual log method that was only included in replay would that work for you?

@pauldambra yes, that would be great; exactly what's needed.

It's purely to ensure we can enrich the session replay capability with logs that are usually filtered out by default, but would be important when reviewing replays for debugging reasons!

**Comment by pauldambra** [comment]
cc @Gilbert09 👀

**Comment by pauldambra** [comment]
@nebbles while investigating something else I realised that we already have a `log` method in session replay

so you can gather logs with recordings by calling `log` on `posthog.sessionRecording` 

https://github.com/PostHog/posthog-js/blob/d08d318214424182c74fa6726e697b7a3dca56d6/src/extensions/replay/sessionrecording.ts#L455

#TIL sorry not to spot this when first replying!

these logs require replay to be active, but once ingested you can query them using HogQL. So, not a full logging solution but might be enough for you to work with 😊
