### ISSUE TITLE
`.capture_links()` and `capture_forms()` are broken

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog-js#125]
`capture_forms()` contains a typo

`capture_links()` seems to redirect users to undefined links instead of href

Added a (failing) test in this branch: https://github.com/PostHog/posthog-js/pull/new/spec-for-capture-links-broken

**Comment by macobo** [comment]
@timgl @mariusandra question time: is it worth patching these or shall we just drop them? 

Both of them have been 100% broken since the initial release and I'd posit they don't really add extra value to the library due to autocapture. Less code for us to maintain going forward as well.

**Comment by mariusandra** [comment]
totally for dropping them

**Comment by timgl** [comment]
Yep agree drop them
