### ISSUE TITLE
2nd page of Survey is not getting shown 

### ISSUE THREAD

**Issue by kiranP007** [PostHog/posthog-js#1262]
In the survey, we have two pages, firstly, on the first page user can add feedback and click on the submit button. Secondly, on the 2nd page user sees a thanks message and can click on the close button to close the survey.

2 days back everything was working. form the day before yesterday, on the 1st page, when we clicked the submit button, we started getting the "c.getNextSurveyStep is not a function" error, for more info check #1258. Anyway, this issue has been fixed now. However, we stopped getting the 2nd page once the 1st page submit button was successful.

We have a 1.128.1 posthog-js version.

![1stpage](https://github.com/PostHog/posthog-js/assets/45927625/79029e42-e30c-4ea4-a996-9b946af743fd)
![2ndpage](https://github.com/PostHog/posthog-js/assets/45927625/ec19395a-afb9-4c55-a1df-88c40c675175)

**Comment by jurajmajerik** [comment]
Hey @kiranP007, this has been fixed, sorry for the trouble!

**Comment by jurajmajerik** [comment]
Hey @kiranP007, this has been fixed, sorry for the trouble!
