### ISSUE TITLE
window.extendPostHogWithExceptionAutocapture is not a function

### ISSUE THREAD

**Issue by paligiannis** [PostHog/posthog-js#1264]
## Bug description

Fresh installation on Digitalocean with 4GB Ram and 120 SSD.
I place the script on my website and started running with session getting pushed on my admin panel. SSL and A record are established correctly. 

<img width="1113" alt="Screenshot 2023-11-10 at 4 20 19 PM" src="https://github.com/PostHog/posthog/assets/10850092/cf0268b8-ebef-44ba-963d-ececd4bc2b6c">

<img width="2222" alt="Screenshot 2023-11-10 at 4 19 45 PM" src="https://github.com/PostHog/posthog/assets/10850092/8e203d53-c9b3-4b36-a2e3-8e9e2ba9fcd8">

## How to reproduce

1. Install on DO Ubuntu 
2. Install with the latest version (Main is docker tag 1.43.1)
3. Apply to a website and then I get this issues

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: [TAG 1.43.1]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by pauldambra** [comment]
this shouldn't be an issue now 1.140.1 is out
