### ISSUE TITLE
"PostHog Person URL" logged in Sentry results in a 404

### ISSUE THREAD

**Issue by freeatnet** [PostHog/posthog-js#1269]
**Environment:** browser, `posthog-js@1.140.1`

**Steps to reproduce:**
1. Set up Sentry with PostHog integration for ease of access to user profiles.
2. Cause an exception to be captured by Sentry.
3. Go to the exception in Sentry and attempt to navigate to the PostHog Person URL link,  `https://app.posthog.com/project/phc_[rest of PostHog project token]/person/[distinct_id]`.

**Expected:** the link opens PostHog person view.
**Observed:** "Page not found" on posthog.com.

**Triage:**
* This link is generated [here](https://github.com/PostHog/posthog-js/blob/main/src/extensions/sentry-integration.ts#L91) using `_posthog.config.token`, so the use of the token seems intentional.
* After the login redirect, the final URL is `https://us.posthog.com/project/[PostHog Project ID]/project/phc_[rest of PostHog project token]/person/[distinct_id]`, which seems to include one too many `/project/[id]` path segments.
* Could the issue be related to the frontend redirect and not the `posthog-js` library itself?

**Comment by pauldambra** [comment]
hey @freeatnet it is the chain of redirects that are being caused by using `app.posthog.com` as the initial URL

what's your posthog config? if you use us.posthog.com directly this won't happen

**Comment by freeatnet** [comment]
@pauldambra Looks like we've been running with `app.posthog.com` in production all this time 🙈 Changing to the geo-based host fixed the issue. Thanks for getting back to me!
