### ISSUE TITLE
Run cypress tests on many browsers via browserstack

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog-js#130]
BrowserStack [has a way to run cypress tests on different browsers](https://www.browserstack.com/docs/automate/cypress)

They also [sponsor open-source](https://www.browserstack.com/open-source) - we could make use of that in our tests.

Sadly no IE11 support though

**Comment by weyert** [comment]
you could consider TestCafe

**Comment by yakkomajuri** [comment]
We have this now
