### ISSUE TITLE
Toolbar "View and edit all actions" link leads to 404

### ISSUE THREAD

**Issue by attaxia** [PostHog/posthog-js#1308]
The link in the lower left of the actions tab of the toolbar leads to a 404 error.
<img width="486" alt="Screenshot 2024-07-18 at 11 50 58" src="https://github.com/user-attachments/assets/a35277e8-fa42-4dc5-b8cd-2c80d076236e">

<img width="600" alt="Screenshot 2024-07-18 at 11 51 26" src="https://github.com/user-attachments/assets/f525b90f-84bc-4401-8ab7-f59f66776eca">

**Comment by pauldambra** [comment]
Hey @attaxia that URL is incorrect `eu.i.posthog.com` is the "ingestion" URL not the "app" url

Also... sorry we totally missed this issue - bad of us!

If this is still happening for you. Try setting `ui_host` to `https://eu.posthog.com`... 

I'll close this - but re-open it if that doesn't work for you!
