### ISSUE TITLE
PostHog events are not coming under Activity tab sometimes some appears sometimes nothing is shown

### ISSUE THREAD

**Issue by kiranP007** [PostHog/posthog-js#1310]
Till 2 days back, everything was working properly, we were getting all events inside activity tab. Not sure what happened but now we are not able to get all events. For example, if 10 events are expected then activity tab shows only 3. 

Observations:
1) Events like div click, clicked button are also not coming
2) Events added by us are also not comming, only 20-30% getting shown.
3) Video recording is coming propertly, but at the bottom earlier we use to see grey dot which used to represent all the events in the video, those dots are reduced drasticly. You can check attached image for more info, only 3 events(grey dots) are present, whereas earlier we used to have lot of event at the bottom.

![greyDots](https://github.com/user-attachments/assets/35141a51-538b-426b-85a2-6c4dcc3a51e3)

Posthog-js version: 1.128.1

**Comment by pauldambra** [comment]
Hey @kiranP007 

There's an open incident at the moment. You can follow along here https://status.posthog.com/

All the events should be visible again once that is finished. If not, can you run through the in-app support flow to let us know

Thanks! (and sorry for the interruption!)
