### ISSUE TITLE
Option to disable sending events and only log them

### ISSUE THREAD

**Issue by TriPSs** [PostHog/posthog-js#1320]
During development it would be quite handy if we could disable the actual sending of events and only log what would have been send.

This will make implementing PostHog events easier and wont pollute the dashboard with test data.

**Comment by benjackwhite** [comment]
This is cool idea. How would you expect the SDK to look like for this?

**Comment by TriPSs** [comment]
The `posthog-node` SDK has a `disabled` option, maybe we can add that to? If `debug` is then enabled it will then log (like now) the events to the console.

**Comment by alimony** [comment]
Yes, this would be great. Useful during development to make sure events would be correctly logged without having to test in a real environment and pollute production data.

**Comment by pauldambra** [comment]
This would be possible using https://github.com/PostHog/posthog-js/pull/1515

I'll update the docs examples we're writing here https://github.com/PostHog/posthog.com/pull/9844
