### ISSUE TITLE
Issue with Immediate Property Update in PostHog

### ISSUE THREAD

**Issue by saad12035** [PostHog/posthog-js#1325]
Hi, I'm working on a Next.js application and have implemented a welcome modal that should only appear once for a user after they sign up. My goal is to show this modal when the user signs up and ensure it is displayed only once.

Here's a snippet of the code for handling the modal closure:

```
const handleCloseModal = async () => {
    posthog.people.set(
      {
        orgTourFinished: true
      },
      undefined,
      async () => {
        await getPostHogUserProperties(userConfig?.userUUID!!);

        enqueueSnackbar('Great job, now go enjoy the App', {
          variant: 'snackbarWithTitle',
          title: 'You finished the tour!',
          autoHideDuration: 5000,
          className: `${styles.snackbar}`,
          anchorOrigin: {
            vertical: isMDDown ? 'bottom' : 'top',
            horizontal: isMDDown ? 'left' : 'right'
          }
        });
      }
    );
};
```

The getPostHogUserProperties function looks like this:

```
export const getPostHogUserProperties = async (userId: string): Promise<PostHogPersonProperties> => {
  const response = await axios.get(
    `https://app.posthog.com/api/projects/${
      process.env.NEXT_PUBLIC_POST_HOG_PROJECT_KEY as string
    }/persons?distinct_id=${userId}`,
    {
      headers: {
        Authorization: `Bearer ${process.env.NEXT_PUBLIC_POST_HOG_API_KEY}`
      }
    }
  );

  dispatch(setPostHogPersonProperties(response.data.results));
  return response.data;
};
```

The issue I'm facing is that the orgTourFinished property does not seem to be set immediately when I fetch the data in the callback function. There is a noticeable delay before the property update is visible in PostHog.

Is there a recommended approach for ensuring that user properties are immediately available after setting them?
Is the method I’m using to track and display the modal in line with best practices for PostHog?

**Comment by benjackwhite** [comment]
There are a few issues here:
1. You shouldn't be able to call the api with your project token. If that api request to `/persons` succeeds that would indicate that you have used a **private API key** which should absolutely not be included in your public application (as it has access to all data). Does that API call work? If you are using this in production then you need to immediately delete that key as it means anyone with access to your website may be able to use all your PostHog data.
2. Ingestion is not instant. Analytics platforms like ourselves do a lot of things to reliably ingest data that can have delays on things like Person property merging. It isn't recommended to treat it like a database as its a very different concept. If you need the person properties, then you should get them from your own API or cache them in the browser.

Can you provide more details to what you are trying to achieve? (Or contact support if you have concerns around the security side of things)

**Comment by saad12035** [comment]
Thank you @benjackwhite for highlighting these issues. I will consider your suggestions and take appropriate action.
