### ISSUE TITLE
Survey mode API trigger a bug when solo loaded

### ISSUE THREAD

**Issue by ThibaudTeachup** [PostHog/posthog-js#1344]
Hello everyone !

I started using Posthog for posting surveys on my website but recently, if I only send one API mode survey on my website, the method getActiveMatchingSurveys() doesn't return anything anymore and I get an error like this :

![image](https://github.com/user-attachments/assets/f55da4ae-10c7-412e-9c82-8709afc52d35)

I was wondering if someone knows why this error occurs or if it's a current bug on the posthog js library.

Thanks in advance !

**Comment by kalpesh-aalore** [comment]
@ThibaudTeachup did you found any answer I am having the same issue it comes as posthog takes time to initialized

**Comment by ThibaudTeachup** [comment]
@kalpesh-aalore I unfortunatly didn't find any solution to this problem. Yeah it looks like an init problem since sometimes it works fine for no reason.

**Comment by pauldambra** [comment]
Awesome, thanks for letting us know!
