### ISSUE TITLE
web-vitals extension loads script from incorrect URL

### ISSUE THREAD

**Issue by Jacksondr5** [PostHog/posthog-js#1346]
Hello, I'm encountering an issue where PostHog is attempting to load the web-vitals script, but is using an incorrect URL: `/ingest/ingest/static/web-vitals.js?v=1.154.2`.  This does proxy through to posthog.com (I see some ASCII art of a hedgehog), but returns a 404.

I'm running a NextJS app with [rewrites as a reverse proxy](https://posthog.com/docs/advanced/proxy/nextjs).  Specifically, these:
<details>
<summary><b>next.config.js</b></summary>

```json5
{
  source: '/ingest/static/:path*',
  destination: 'https://eu-assets.i.posthog.com/static/:path*',
},
{
  source: '/ingest/:path*',
  destination: 'https://eu.i.posthog.com/:path*',
},
{
  source: '/ingest/decide',
  destination: 'https://eu.i.posthog.com/decide',
},
```
</details>

My calls to the `/ingest/decide` and `/ingest/e` endpoints are working properly.

Looking through the code, I think the issue may be [this call to endpointFor](https://github.com/PostHog/posthog-js/blob/f5a0d12603197deab305a7e25843f04f3fa4c99e/src/utils/request-router.ts#L84).  When I run through the code in the Chrome debugger, I can see that endpointFor gets called and prepends the extra /ingest that's causing the issue:
![image](https://github.com/user-attachments/assets/edafc2d1-f82e-48e1-b4c9-a04ccdc55ead)

Happy to contribute a PR to a solution.  Not entirely sure what that solution should be.  

My thoughts are to replace 
https://github.com/PostHog/posthog-js/blob/f5a0d12603197deab305a7e25843f04f3fa4c99e/src/extensions/web-vitals/index.ts#L73-L75

with
```typescript
this.instance.requestRouter.loadScript(
    `/static/web-vitals.js?v=${Config.LIB_VERSION}`,
```

This would mean that endpointFor only gets called once, by loadScript.

There are other extensions that do this, instead of also calling endpointFor themselves ([tracing-headers](https://github.com/PostHog/posthog-js/blob/f5a0d12603197deab305a7e25843f04f3fa4c99e/src/extensions/tracing-headers.ts#L21), [toolbar](https://github.com/PostHog/posthog-js/blob/f5a0d12603197deab305a7e25843f04f3fa4c99e/src/extensions/toolbar.ts#L167), [surveys](https://github.com/PostHog/posthog-js/blob/f5a0d12603197deab305a7e25843f04f3fa4c99e/src/posthog-surveys.ts#L77)).  However, [autocapture](https://github.com/PostHog/posthog-js/blob/f5a0d12603197deab305a7e25843f04f3fa4c99e/src/extensions/exception-autocapture/index.ts#L61) does make the same kind of call that web-vitals does, so I'm not sure if this is correct.

**Comment by junioryono** [comment]
+1

I am also receiving this error for web vitals. I have a NextJS app with rewrites as a reverse proxy.

**Comment by junioryono** [comment]
The simplest solution as of now is to add the path in your list of rewrites

### next.config.js
```
async rewrites() {
    return [
      {
        source: "/ingest/ingest/static/:path*",
        destination: "https://us-assets.i.posthog.com/static/:path*",
      },
      {
        source: "/ingest/static/:path*",
        destination: "https://us-assets.i.posthog.com/static/:path*",
      },
      {
        source: "/ingest/:path*",
        destination: "https://us.i.posthog.com/:path*",
      },
      {
        source: "/ingest/decide",
        destination: "https://us.i.posthog.com/decide",
      },
    ];
  },
  ```

**Comment by pauldambra** [comment]
great write up @Jacksondr5 thank you! Super clear

really we should make `endpointFor` safe for multiple calls but in the meantime I've opened #1365 that will resolve this

**Comment by lyonz** [comment]
I just updated to newest version and still have this issue, has it been resolved? or do I need to use @junioryono workaround? Thank you
