### ISSUE TITLE
Error importing `exception-autocapture` when `disable_external_dependency_loading=true`

### ISSUE THREAD

**Issue by jwayne** [PostHog/posthog-js#1349]
## Bug description

When I follow the Posthog docs here to disable external loading of extensions: https://posthog.com/docs/session-replay/installation#advanced-option---bundle-all-required-extensions

I get a terminal error when I run `npm run dev` and access any page:

```
 GET / 500 in 36ms
 ⨯ TypeError: Cannot set properties of undefined (setting 'posthogErrorWrappingFunctions')
    at __webpack_require__ (/Users/joshchen/proj/learning/test-posthog/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/analytics.ts:9:95)
    at (ssr)/./src/app/analytics.ts (/Users/joshchen/proj/learning/test-posthog/.next/server/app/page.js:173:1)
    at __webpack_require__ (/Users/joshchen/proj/learning/test-posthog/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/AnalyticsProvider.tsx:9:72)
    at (ssr)/./src/app/AnalyticsProvider.tsx (/Users/joshchen/proj/learning/test-posthog/.next/server/app/page.js:162:1)
    at Object.__webpack_require__ [as require] (/Users/joshchen/proj/learning/test-posthog/.next/server/webpack-runtime.js:33:42)
digest: "1030166450"
```

This is in posthog-js v1.155.0

## How to reproduce

I have a minimal repro [in this repo](https://github.com/jwayne/test-posthog), where I:
- Installed Posthog into a clean NextJS starter app
- Call `posthog.init` with `disable_external_dependency_loading: true`
- Import all the recommended extensions as per these docs: https://posthog.com/docs/libraries/js#advanced-option---bundle-all-required-extensions

    ```
    import "posthog-js/dist/recorder"
    import "posthog-js/dist/surveys"
    import "posthog-js/dist/exception-autocapture"
    import "posthog-js/dist/tracing-headers"
    import "posthog-js/dist/web-vitals"
    ```

I noticed that if I comment out the 3rd line (`import "posthog-js/dist/exception-autocapture"`) then this error disappears. This is my workaround for now.

## Additional context

I want to use `disable_external_dependency_loading: true` because I want to run posthog in a Chrome extension, and Chrome extensions disallow external script loading.

### Debug info

```
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/01912906-0908-7899-bf74-dc5282c904ce?t=0
Admin: http://go/adminOrgUS/01911fa4-88e3-0000-9070-c8765035ffa5 (project ID 83184)
Sentry: http://go/sentryUS/83184
```

*Note: Issue [originally posted in PostHog repo](https://github.com/PostHog/posthog/issues/24226), then I realized this might be a better place.*

**Comment by pauldambra** [comment]
cc @daibhin
