### ISSUE TITLE
Versions 1.155.5 and up are erroneously including @types/web as runtime dependencies

### ISSUE THREAD

**Issue by fluffynuts** [PostHog/posthog-js#1366]
I had failing builds at GHA today, and it turns out the culprit is a clash between typescript built-ins (`lib/lib.dom.d.ts`, typescript version `4.9.5` (yes, I'm aware that's not the current latest, but we have had some issues with upgrade in the past, so it's been pegged there for a while)) and `@types/web`, which this package is now pulling in.

As far as I'm aware, `@types/*` packages should _always_ be devDependencies, _never_ production ones.

For now, I have to blacklist all versions of posthog > 1.155.4. I would be very surprised if I were the only person experiencing this.

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-js/pull/1358/files
@robbie-c should it be `devDependencies`?

**Comment by robbie-c** [comment]
Yeah, sorry about that @fluffynuts. There's a PR to fix it here: https://github.com/PostHog/posthog-js/pull/1367/files
