### ISSUE TITLE
Fall back on XHR when sendBeacon returns false

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog-js#137]
As per https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon:

> The sendBeacon() method returns true if the user agent successfully queued the data for transfer. Otherwise, it returns false.

We currently send requests using sendbeacon on unload and also allow setting it as a transport option in `.capture` calls or in config.

Let's fall back on XHR when this fails.

Other interesting reading: https://volument.com/blog/sendbeacon-is-broken

Question to @timgl - why do we expose transport as an option in the first place?

**Comment by pauldambra** [comment]
things have changed a tonne... let's close this
