### ISSUE TITLE
Multiple Session Recording warnings when disable_session_recording = true

### ISSUE THREAD

**Issue by vonBrax** [PostHog/posthog-js#1378]
## Bug description

When initializing posthog with `disable_session_recording: true`, after a few interactions with the app, at some point some warnings start showing in the console:

![image](https://github.com/user-attachments/assets/dba2f0f7-7028-454e-9e46-8ae08131cdc9)

Even though no api calls are made, which seems to be respecting the `disable_session_recording` property, the presence of this logs may induce the customer to think that their session is being recorded and that our application is violating their privacy settings.

The problem seems to be happening because the SessionRecorder constructor is called and immediatelly starts listening to some browsers events:

https://github.com/PostHog/posthog-js/blob/9c8fe0e35f6566be7d0e37642c33ed7727fc68bb/src/extensions/replay/sessionrecording.ts#L247-L264

I'm assuming that then the events are added to a queue, which also seems to have a limit of 5 entries, and if the entries can't be processed - probably because session recording should be disabled -, then the warnings start showing up.

## Additional info

We are using the bundled version of posthog as described in the [docs](https://posthog.com/docs/libraries/js#advanced-option---bundle-all-required-extensions), which means that the session-recorder module is not lazy-loaded by posthog, and seems to be instantiated regardless of the posthog init config.

## Steps to reproduce
1. Bundle posthog and it's dependencies
2. Start the app and initialize posthog with `disable_session_recording: true`
3. Trigger the `visibilitychange` event 5 times (for example switching to a different tab or ALT+TAB to a different running application)
4. After that, any subsequent `visibilitychange` event will cause a _SessionRecording_ warning to be displayed in the browser console

**Comment by pauldambra** [comment]
hey @vonBrax 

just updating you that there's some CI fixing happening in our end-to-end tests and I'm out of the office till tuesday so I think it will be tuesday before the fix is merged

sorry, we're normally faster than that)

**Comment by vonBrax** [comment]
Hey @pauldambra, no worries. Thank you for the update and for the quick fix here!

**Comment by pauldambra** [comment]
This should be resolved in 1.158.1

Do let us know if not!

**Comment by vonBrax** [comment]
I can confirm that the issue is fixed in 1.158.1.

Thank you @pauldambra !

**Comment by pauldambra** [comment]
Great news, thanks for the detailed report @vonBrax 🙌
