### ISSUE TITLE
'img' config option does not work

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog-js#138]
`img` config option is supposed to create an image tag and do a request to the server based on the url in src attribute. 

Sending the request _almost_ works, except it doesn't encode the event name or properties into the url it generates.

**Comment by macobo** [comment]
Actually, sending data via GET would fail for the same reason.

The bug is the same for both - we should put the data into the URL via `args`: https://github.com/PostHog/posthog-js/blob/master/src/posthog-core.js#L409-L411

Haven't tested if this would work on posthog-side though.

@timgl @mariusandra thoughts on this? Shall we a) fix this or b) drop the unsupported behavior?

**Comment by mariusandra** [comment]
I'd drop. We're not really targeting `IE8` or whoever anymore. Making a bunch of DOM nodes just to send `GET` requests seems silly.

**Comment by pauldambra** [comment]
removed in #651
