### ISSUE TITLE
How to properly disable `debug` mode on development?

### ISSUE THREAD

**Issue by stefanobartoletti** [PostHog/posthog-js#1387]
I'm using posthog on a Nuxt website, which I have integrated by following this guide https://posthog.com/docs/libraries/nuxt-js

I'm currently flooded in my browser console by a lot of posthog events, just like this

![Screenshot_20240827_115458](https://github.com/user-attachments/assets/eafd61f5-95a8-4ed3-b388-588c221926a8)

I'm trying to disable all these unneeded messages, but I'm not really sure about what is the proper way to do this.

In my init, I've tried to both explicitly NOT calling the debug mode and to set it to false, like this:

```js
  const posthogClient = posthog.init(runtimeConfig.public.posthogPublicKey, {
    api_host: runtimeConfig.public.posthogHost || 'https://eu.i.posthog.com',
    person_profiles: 'identified_only',
    capture_pageview: false,
    debug: false, // <-- explicitly setting debug to false
    loaded: (posthog) => {
      // if (import.meta.env.MODE === 'development') posthog.debug(); // <-- NOT called the debug mode on development
     console.log('PostHog config:', posthog.config)
    }
  })
```

But even like this, the config that I'm logging is displaying `debug: true`

![Screenshot_20240827_121219](https://github.com/user-attachments/assets/229829b4-4053-4333-984d-53db5eb6cb5a)

Am I doing something wrong, or there is some bug in the package? How can I completely disable the debug logging?

**Comment by pauldambra** [comment]
hey @stefanobartoletti 

to help narrow down what's going on here...

can you try clearing local storage or launching in an incognito window? i'm wondering if we're storing the debug flag and then incorrectly preferring that stored value

**Comment by benjackwhite** [comment]
I think the issue is that calling `.debug()` sets a flag in local storage. Calling `.debug(false)` clears it whereas having it as `false` in the config doesn't.

**Comment by yoni-noma** [comment]
using .debug(false) solve it only if i refresh the page, is there a workaround?

**Comment by mike-pete** [comment]
I really wanted to set PostHog's debug via an env variable so it's easy to toggle off when you don't need it. But when you explicitly disable debug (`debug(false)`) it logs to the console.

I don't want this extra log in the prod console. So this is what I ended up on:

```ts
loaded: posthog => {
  if (process.env.NEXT_PUBLIC_POSTHOG_DEBUG === 'true') {
    posthog.debug(true)
  } else if (localStorage.getItem('ph_debug')) {
    posthog.debug(false)
  }
},
```
