### ISSUE TITLE
PostHog can't re-init after reset 

### ISSUE THREAD

**Issue by joebnb** [PostHog/posthog-js#1388]
i want isolate user data and staff data in one application.

this plan designed create 2 project to save different user‘s log, one is for anonymous user and logged in user，other is for staff.

the process like:

```js
posthog.init(API_KEY_GLOBAL) 

login.request().then(()=>{

    if(isStaff){
        posthog.reset().then(()=>{
    
            posthog.init(API_KEY_STAFF)
            console.log(posthog) // fig1

        })
    }

});
```
the fig1 still log  API_KEY_GLOBAL instance, i think it should be use API_KEY_STAFF to report log data

**Comment by therealabdi2** [comment]
Did you figure this out? Facing the same issue

**Comment by joebnb** [comment]
> Did you figure this out? Facing the same issue

seems the upper mentioned pr are not about this issue,there still no method to change different posthog project to isolate user  in runtime

**Comment by rafaeelaudibert** [comment]
Hey @joebnb @therealabdi2. You're correct that calling `reset` won't help you here, this is not what it was meant to be used for.

You can achieve your goals by using the third parameter to `posthog.init`. It allows you to name your posthog instance.

```javascript
posthog.init(GLOBAL_TOKEN, {}, 'global')
posthog.init(STAFF_TOKEN, {}, 'staff')
```

You can then call the different keys by accessing that instance inside the global `posthog` instance

```javascript
posthog.global.capture(...)
posthog.staff.capture(...)
```

I'm working on some new docs to make that clearer in our documentation, this is a very hidden feature. I'll update you once I have better documentation around this - by the end of the day today.

**Comment by therealabdi2** [comment]
@rafaeelaudibert but with 2 instances running, wont this cause duplicate session replays?

**Comment by rafaeelaudibert** [comment]
> @rafaeelaudibert but with 2 instances running, wont this cause duplicate session replays?

@therealabdi2 That is true, but for that reason you'll likely want to turn off autocapture, automatic session replays, etc. and manually trigger them when needed.

This is a very niche use case, so you're going to find some bumps on your way when attempting to use Posthog like this.

Do you mind clarifying why is it that you need two posthog instances at the same time? What's the specific use case for you?

**Comment by therealabdi2** [comment]
@rafaeelaudibertIn in our app, users can select their organization, and based on that, we need to set the appropriate PostHog API key. Each organization has its own PostHog project to ensure data segregation. While events are managed on the backend and routed to the correct posthog project without issue, session replays can only be managed by posthog on frontend and need to be routed to their respective projects.

**Comment by rafaeelaudibert** [comment]
@therealabdi2 Got it, I agree that's a slightly different issue to the issue Joe raised here.

I haven't tried this, and I don't think we'll always be able to support this as this would be undocumented, but you could always say the following

```typescript
import Posthog from 'posthog-js/core'

window.posthog?.reset()
window.posthog = new PostHog()
window.posthog.init(...)
``` 

This should clear everything completely and allow you to reconfigure the instance completely. Would you mind testing this?

**Comment by therealabdi2** [comment]
@rafaeelaudibert yup that works, thanks
