### ISSUE TITLE
sentryIntegration sends errors to an incorrect endpoint with a relative api host

### ISSUE THREAD

**Issue by j3ski-bioraptor** [PostHog/posthog-js#1389]
My posthog init code is as follows:
```ts
const client = posthog.init(<api_key>, {
      api_host: '/posthog',
    })
```
And then I create the sentry integration:
```ts
client.sentryIntegration({
    organization: <orgId>,
    projectId: <projectId>,
  })
```

Posthog sends events correctly to `<my_domain>/posthog/s/`, however when an error is thrown the error is reported to `<my_domain>/e/`, instead of `<my_domain>/posthog/e/`.

I tried changing the init code to use `window.location.origin + '/posthog'`, but with not effect.

**Comment by neilkakkar** [comment]
thanks @j3ski-bioraptor looks like a bug on our side, looking into this!
