### ISSUE TITLE
`url_ignorelist` on Autocapture config doesn't seem to be working

### ISSUE THREAD

**Issue by jperezr21** [PostHog/posthog-js#1402]
I want to ignore events from the Vercel screenshots crawler (user agent `vercel-screenshot/1.0`).

These events have `$current_url` set to `https://project-and-deployment-id.vercel.app/`.

I tried adding all of the following:
```
    autocapture: {
      url_ignorelist: [/.*\.vercel\.app\/.*/, "vercel.app", "vercel.app/.*"],
    },
```
but I'm still receiving these events.

Am I doing something wrong or is this a bug?

**Comment by pauldambra** [comment]
Hey,

Are you receiving only `$autocapture` events? That ignore list is to stop only `$autocapture` events (like clicked on a div)

I'd expect it's better to edit the user agent blocker... So, in your config you can set _additional_ user agents we'll detect as bots in your config you'd set `custom_blocked_useragents: ['vercel-screenshot/1.0]`

(ofc if you're fine with other events and its just autocapture you want to block we can check that too :))

**Comment by jperezr21** [comment]
These are `$pageleave` events, which I have enabled in the config. So maybe they aren't `$autocapture`. Here's my whole config:
```ts
  posthog.init(env.NEXT_PUBLIC_POSTHOG_KEY, {
    api_host: "/ingest",
    ui_host: "https://app.posthog.com",
    person_profiles: "identified_only",
    capture_pageview: false,
    capture_pageleave: true,
    autocapture: {
      url_ignorelist: [/.*\.vercel\.app\/.*/, "vercel.app", "vercel.app/.*"],
    },
  });
```
I'll try adding `custom_blocked_useragents` param.

Thanks!

**Comment by jperezr21** [comment]
Turns out Vercel doesn't always set the user agent to that 🤦 

Their latest request came with `Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`.

There should be a global `url_ignorelist` option.

**Comment by pauldambra** [comment]
Hey,

In the short term.. you can detect the URL and not initialize posthog which is equivalent to a url ignore list (if slightly more work on your part) and should work if you never want to collect on that URL... similar to how folk check if they're running on localhost and don't send data.

I think this is maybe another vote for a global `onEvent` or similar that lets folk mask / edit / reject events. In your case it'd be `if (url === blah) return null` 🤔

**Comment by pauldambra** [comment]
we added `before_send` as an option on posthog-js which could be used for this
