### ISSUE TITLE
Discussion: Base64 encoding?

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog-js#141]
I'm wondering what our rationale is for base64 encoding our data at this point.

The endpoints used to only accept base64 data, but [that was changed](https://github.com/PostHog/posthog/pull/1592) (actually by me).

So there are a few points that come to mind:

**Pros**
- Being able to understand the request data in the network tab 
- We should be able to kill a [bunch more code](https://github.com/PostHog/posthog-js/blob/master/src/lz-string.js)?

**Cons**
- Same as Pros number 1: Request data will be more transparent
- ...?

@macobo

**Comment by macobo** [comment]
Most requests get compressed via lzstring (not base64) at this point in time https://github.com/PostHog/posthog-js/blob/master/src/posthog-core.js#L338-L344.

The reason for this compression is to save clients data - the smaller the request, the better in that regard. This plays a huge part especially with session recording.

**Comment by yakkomajuri** [comment]
Ah yes of course! Makes perfect sense

**Comment by mariusandra** [comment]
Indeed, we `base64` the data sent to the server, but we compress it first with `lzstring`. Unfortunately there's no built-in compression API in every browser that we could use, so we need to bundle it. LZString is great for this, as it's [just 5kb minified](https://bundlephobia.com/result?p=lz-string@1.4.4) and compresses pretty well. `base64`'ing the compressed data makes the request [33%](https://en.wikipedia.org/wiki/Base64) bigger again. We could switch to [base85](https://en.wikipedia.org/wiki/Ascii85) to save 7%, but that's meh.

One true optimisation we can do is to attach the payload as a regular uploaded file through [`multipart/form-data`](https://stackoverflow.com/a/28080392/624476).
