### ISSUE TITLE
Cannot read properties of undefined (reading 'onLCP')

### ISSUE THREAD

**Issue by yoni-noma** [PostHog/posthog-js#1412]
### Bug Description
Im getting lots of this error, not sure if its impacting the user experience.

## Additional context
my project is a Remix project, initiating posthog on the root->App component

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/0191dff6-69e3-7e3e-aa7e-6383a3dd3e7d?t=0
Admin: http://go/adminOrgUS/0191d1cd-cd06-0000-dbc1-4ad44b390154 (project ID 89869)
Sentry: http://go/sentryUS/89869


```

**Comment by abigailbramble** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/17947 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20109)
+1 https://posthoghelp.zendesk.com/agent/tickets/18020 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20386)
+1 https://posthoghelp.zendesk.com/agent/tickets/18023 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19934)

**Comment by pauldambra** [comment]
Ah, no I think I see what's happened here... Let me see if I can resolve this on our side.

Will update shortly

**Comment by pauldambra** [comment]
I believe this is resolved now!

**Comment by rvanlaarhoven** [comment]
Yes, seems to be resolved on my end at least. Haven't seen the error since a couple days now.

**Comment by pauldambra** [comment]
Amazing, thanks for confirming

**Comment by ebimohi** [comment]
@pauldambra Hi!
I face the similar issue and we use posthog-js ver 1.149.1
I didn't find out how this issue resolved and wondered to get what is the culprit and how we can get rid of this issue, please advise. thanks in advance!

**Comment by pauldambra** [comment]
hey @ebimohi the best thing to do update to the latest version you can and then open a support ticket in-app if it's still happening - the underlying issue here was fixed with a PR to the code so if you're still getting it on latest posthog-js then something else is going on

thanks
