### ISSUE TITLE
Conflict with react-query devtools

### ISSUE THREAD

**Issue by tyteen4a03** [PostHog/posthog-js#1425]
When I have both PostHog Toolbar and React Query DevTools in my application, toggling Feature Flags stop working.

**Comment by pauldambra** [comment]
hey @tyteen4a03 

Can you share more info about what happens? Do you see any errors in the network panel or the console?

Is that this dev tools? https://tanstack.com/query/latest/docs/framework/react/devtools

**Comment by tyteen4a03** [comment]
> hey @tyteen4a03 
> 
> Can you share more info about what happens? Do you see any errors in the network panel or the console?
> 
> Is that this dev tools? https://tanstack.com/query/latest/docs/framework/react/devtools

No warnings or errors, clicking on the toggle just instantly closes the toolbar without actually toggling the FF.

Yes, that's the package.

**Comment by pauldambra** [comment]
Wild... do other interactions in the toolbar work?

**Comment by tyteen4a03** [comment]
> Wild... do other interactions in the toolbar work?

I just checked again, none of the click interactions work.

**Comment by rmanganiello** [comment]
Hey folks!

I was having the same issue and I realized that this is because Tanstack Query Devtools is adding a `mousedown` event listener that generates this wrong behavior:

![image](https://github.com/user-attachments/assets/aff8a5b6-9673-421f-90cf-5667c540bf29)

![image](https://github.com/user-attachments/assets/906966d9-d2e4-4200-a330-0c71e78c5838)

In order to prevent this, I created a React component that adds a new event listener for the `mousedown` event type, stopping propagation to other event listeners.

```jsx
import { useEffect } from 'react';

export const PosthogToolbarGuardAgainstTanstackDevtools = () => {
  useEffect(() => {
    let observer: MutationObserver | null = null;

    // Function to check and attach the event listener if the element is present
    const checkAndAttachListener = () => {
      const posthogToolbar = document.getElementById('__POSTHOG_TOOLBAR__');

      if (posthogToolbar) {
        const stopEvent = (e: MouseEvent) => {
          e.stopImmediatePropagation();
        };
        posthogToolbar.addEventListener('mousedown', stopEvent);

        // Cleanup function to remove the event listener and disconnect the observer
        return () => {
          posthogToolbar.removeEventListener('mousedown', stopEvent);
          if (observer) observer.disconnect();
        };
      }
    };

    // Observer callback triggers when any changes in child elements of the body occur
    observer = new MutationObserver(checkAndAttachListener);
    observer.observe(document.body, { childList: true, subtree: true });

    // Return cleanup function to disconnect observer on unmount
    return () => {
      if (observer) observer.disconnect();
    };
  }, []);

  return null;
};
```
You can use this component inside the `PostHogProvider` component like this:

```jsx
            <PostHogProvider apiKey={import.meta.env.VITE_POSTHOG_API_KEY} options={posthogOptions}>
              <PosthogToolbarGuardAgainstTanstackDevtools />
              {children}
            </PostHogProvider>
```

Let me know if this works for you!

**Comment by tyteen4a03** [comment]
@rmanganiello thank you! Do you think this is an issue on TanStack's end?

**Comment by rmanganiello** [comment]
Not sure yet, I need to keep checking the Tanstack Devtools Library to understand where the issue is generated.

**Comment by rafaeelaudibert** [comment]
Thanks @rmanganiello! I've basically implemented your solution inside the toolbar, and it seems to be working perfectly locally - which is probably the only place where you're seeing their devtools, right?

https://github.com/PostHog/posthog/pull/26849

**Comment by rmanganiello** [comment]
Hey @rafaeelaudibert, yes, that's correct, I have Tanstack Query Toolbar enabled only in my local environment.

Thanks a lot for the fix in the library itself so I can get rid of my workaround once the new version gets released!

Cheers!
