### ISSUE TITLE
BigInt serialization error in encodePostData

### ISSUE THREAD

**Issue by zimrain** [PostHog/posthog-js#1440]
Our React app uses BigInt in many places. Only autocapture is on, no custom events. We're getting the following: "TypeError: Do not know how to serialize a BigInt"

Source map points back to `JSON.stringify` call in `encodePostData` here: https://github.com/PostHog/posthog-js/blob/26150b197dc1a2f5241b8d29ee7a359331a1a0a4/src/request.ts#L48

**Comment by jonahallibone** [comment]
same error here

**Comment by TommySoFM** [comment]
Having the same issue here too.
Have to turn off auto-capture to stop the error from appearing

**Comment by robbie-c** [comment]
Hi @zimrain - it'd be pretty easy for us to serialize BigInts as a string, but can you explain how a BigInt might have gotten into an event payload? E.g. are you setting it as a user property? It'd be good to know what steps I'd need to take to reproduce this issue and confirm my fix on.

**Comment by zimrain** [comment]
Just auto-capture, we didn't have any manual events/properties

**Comment by robbie-c** [comment]
Do you use data attributes to add extra properties? https://posthog.com/docs/product-analytics/autocapture#tracking-metadata
