### ISSUE TITLE
nextjs setup feedback

### ISSUE THREAD

**Issue by mmkal** [PostHog/posthog-js#1461]
Hi, I'm setting up posthog on a new project, and thought I'd share some unsolicited feedback as I'm going through it.

There are a few things that are stressing me out somewhat as I set it up. I'm not usually a frontend developer, but I'm aware of most of the common webdev pitfalls, and the main theme of my feedback is that those pitfalls, or the tradeoffs associated with them, are not talked about enough.

## [App router setup](https://posthog.com/docs/libraries/next-js#app-router)

The app router docs suggest creating a `PHProvider` component with `'use client'`, and wrapping your entire application in it. There's mention of de-opting the entire page into client side rendering later, in the PostHogPageView component, but not here. It's my understanding that putting the whole app inside a client component will also make the whole page a client component (with child server components being "holes"). If I'm wrong about that, it'd be good to see some reassurance that it's no big deal to slap a `'use client'` directive so high up in the app. If I'm right, then I'd like to see the alternatives. Will I still be able to use posthog if I don't put everything inside its provider? I would have hoped so, since you can also load posthog as a snippet. What would I lose by doing it this way? Will I still get autocapture?

The note about the mismatch warning: this kind of thing is really confusing and hard to debug, so I'm not sure why the default advice is to set it up in a way that _causes_ a mismatch warning - why not just replace the `if (typeof window !== 'undefined')` version with the `useEffect` version and simplify things? Is there any _advantage_ to the `typeof window` approach? If so, what is it? If not, why is that approach still documented?

Then, with the `useEffect` approach - again, I'm not a web dev, but I've read enough blogs and tweets to think useEffect = bad, and to remember phrases like "[you might not need an effect](https://react.dev/learn/you-might-not-need-an-effect)". Re-reading that article, it looks like what we're doing here, and maybe in PostHogPageView could be better served by useSyncExternalStore, maybe? The [example in the article](https://react.dev/learn/you-might-not-need-an-effect#subscribing-to-an-external-store) is a similar `window.addEventListener(...)` type thing.

PostHogPageView: again we've got a useEffect, which is now combined with useSearchParams and usePathname. I can see the logic in that, but I also wondered why we need to do it that way, and how important it is to keep it _exactly_ as documented on the setup page. I also had a look at some nextjs docs for similar libraries, and they mention that [Google Analytics can track page views](https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#tracking-pageviews) by listening to browser history state changes (presumably `window.navigation.addEventListener('navigate', ...)`. I tried this on my own website and it works well:

<img width="945" alt="image" src="https://github.com/user-attachments/assets/b165be59-2e29-4ffb-99be-3080ef16d614">

## [Pages router](https://posthog.com/docs/libraries/next-js#pages-router)

I have some pages still in the pages router (using nextra, so they're markdown - understandable not to explicitly cover this case though). This was a little less stressful since there's no worry about making the whole app a client component (as far as I understand, everything in pages router already is a client component).

But the question about `useEffect`, and whether it's necessary, remains, and in fact there's a little additional confusion because unlike in the app router section, there's no `capture_pageview: false` in the init command, even though it looks like we're still being advised to capture $pageview manually. Again, it seems like it would be possible for posthog to do all this for us by using `window.navigation.addEventListener` - and by avoiding any `next` libraries, everything could be encapsulated inside `posthog-js/react`, and greatly simplify the setup. It would also presumably mean it it "just works" for any other React SPA framework.

---

More notes:

- Checking browser compatibility since writing that, it seems FireFox doesn't have `window.navigation.addEventListener` yet. But still, rather than making all PostHog users worry about this, there are workarounds for this that I suspect in most cases would be acceptable, esp. given the majority of visitors will be on chromium browsers: https://stackoverflow.com/a/4585031
- There's some discussion in the comments about this, including a [(merged?) docs update](https://github.com/PostHog/posthog.com/pull/6262/files) that adds `<Suspense>` to avoid problems with `useSearchParams` - however this update doesn't seem to have made it to the page? Or maybe it's been superseded by the dynamic import suggestion. Either way, I think posthog figuring out when browser state updates independently of nextjs-specific APIs would still be preferable and avoid all this confusion.

**Comment by ivanagas** [comment]
Got a [PR](https://github.com/PostHog/posthog.com/pull/9628) addressing this feedback:
- FAQ addresses de-opting, what the value of the `PostHogProvider` is, `useEffect` vs `window` check for initialization, and why use a `useEffect` for pageviews
- When we initialize PostHog, we aren't waiting for an external store to load. We are waiting for the app to load, which React says you can use `useEffect` to do.
- It is hard to recommend `window.navigation` when it is not supported by a significant number of browsers. Would lead to a significant number of dropped events. 

Will work on pages router updates next. Web analytics team also has improving the Next.js experience on their roadmap this quarter: https://posthog.com/teams/web-analytics#roadmap

**Comment by mrmuke** [comment]
Hey guys, there is a major issue after you moved posthog.init into a useEffect, when using usePostHog, posthog isn't immediately loaded. I spent quite a while figuring out why posthog doesn't load in child components immediately. Julian, the most recenet comment on the nextjs docs (https://posthog.com/docs/libraries/next-js), seemed to realize this issue as well.

**Comment by delfincortesb** [comment]
@mrmuke I read someone found a fix on the docs page:

> I encountered the same issue as you and was able to fix it by **moving the posthog.init outside of the useEffect** into the window. Hope that helps!

here's the link: https://posthog.com/docs/libraries/next-js
