### ISSUE TITLE
onScriptLoaded was called but rrwebRecord is not available. This indicates something has gone wrong. Session record isn't being sent.

### ISSUE THREAD

**Issue by sc4lr** [PostHog/posthog-js#1471]
### Problem:

Session recordings aren't being sent. There's no `/s` request in the network tab and as well as in the **session replay** tab in posthog.

### Details:

I turned on debug mode in order to investigate the problem. What I've noticed is that I'm getting the following error starting from `"posthog-js": "1.163.0"`.

```
[PostHog.js] [SessionRecording]onScriptLoaded was called but rrwebRecord is not available. This indicates something has gone wrong.
```

### Browsers

This problem occurs in every browser I tried, therefore it doesn't seem to be related to specific browser.

- **Arc:**
Version 1.63.1 (54714)
Chromium Engine Version 129.0.6668.101

- **Google Chrome:**
Version 129.0.6668.100 (Official Build) (arm64)

- **FireFox:**
131.0.3 (aarch64)

**Comment by pauldambra** [comment]
Hey,

Does this happen for you in other versions of posthog-js e.g. latest?

Is the site public for us to take a look at what is happening?

**Comment by sc4lr** [comment]
Hi! Thanks for a quick response!

Yep, same problem using `1.168.0` (latest) version of posthog-js

<img width="815" alt="image" src="https://github.com/user-attachments/assets/1f3c12f3-870f-4056-87d3-9123b3716129">

No, unfortunately it is private self-hosted domain. Do you think it might be the problem on our side?

**Comment by sc4lr** [comment]
Sorry, did you mean site with enabled debug mode posthog? If so, I'm afraid I'll not be able to deploy configuration with enabled debug mode on prod

**Comment by pauldambra** [comment]
Hard to say what's happening without access to the site :)

When you enable recording, we will download `recorder.js` and execute that file, which adds some info to window

`window.__PosthogExtensions__.rrweb`
and for backwards compatability
`window.rrweb`

Do you see any errors loading our JS files or other errors in the console?

> If so, I'm afraid I'll not be able to deploy configuration with enabled debug mode on prod

if you visit the site with `?__posthog_debug=true` in the URL posthog boots in debug mode :)

**Comment by sc4lr** [comment]
No errors loading `recorder.js?v=1.168.0` file and no any other errors in the console.

Is it okay that there's no `window.__PosthogExtensions__.rrweb`?

<img width="476" alt="image" src="https://github.com/user-attachments/assets/5442f4c9-21b3-49de-bcf9-a03a4e69c96f">

**Comment by pauldambra** [comment]
<img width="407" alt="image" src="https://github.com/user-attachments/assets/3815be13-0ff2-4a1f-8cd5-ffaaf935ac27">

Ah, I've just realised you said this was a private self-hosted domain? Do you mean it's a self-hosted posthog?

We've not used rrweb v1 for more than 6 months

**Comment by sc4lr** [comment]
Yes, it is self-hosted posthog. Is there a problem on it's side?

**Comment by pauldambra** [comment]
What version of self-hosted posthog is it?

**Comment by pauldambra** [comment]
You can't necessarily load arbitrary posthog-js versions when self-hosting. Each self-hosted version has a version of posthog-js that it will serve (e.g. my self-hosted posthog-js is at https://ph.pauldambra.dev/static/recorder.js?v=1.167.0)

**Comment by sc4lr** [comment]
Well, you're right. We're using ancient version of posthog. I was told that this was a necessary decision

Anyway, thank you so much for your help and so much useful information
