### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog-js#149]
A user reported a need for IE11 support (their use case is running PostHog on an embedded MS Word app). He mentioned that there's an issue with bundled dependencies not being compatible with IE11. The user shared his code for converting them with Babel (note that the snippet contains dependencies for Papercups, which they also use in their app).

```javascript
 {
          test: /\.(ts|js)x?$/,
          loader: "babel-loader",
          // most of these are papercups transitive properties
          exclude: /node_modules\/(?!(?:@papercups-io|posthog-js|query-string|@emotion|strict-uri-encode|camelcase-keys|camelcase|map-obj|quick-lru|split-on-first|framer-motion))/
}
```

**Comment by macobo** [comment]
Any way to get the user involved here?

What version of the library were they using? As per https://github.com/PostHog/posthog-js/blob/master/CHANGELOG.md, 1.7.2 included improvements here.

**Comment by jamding** [comment]
`    "posthog-js": "^1.5.2",` let me upgrade

**Comment by macobo** [comment]
Great! I think we can close this for now.
