### ISSUE TITLE
Feature request: track initial person properties for anonymous events when a changes subdomain then is identified

### ISSUE THREAD

**Issue by robbie-c** [PostHog/posthog-js#1524]
With anonymous events, a person profile isn't created until `identify()` is called. If this happens on the initial site, the initial referrer and initial campaign properties are sent with the identify event, as these are stored in localStorage from the initial visit, so the person profile that gets created will have correct values.

If the user changes subdomain (e.g. from a marketing site to a product site) before identifying, this info in localStorage is lost, so the person is created with the wrong initial referrer.

There are a few ways that users can fix or mitigate this at the moment:
* Set person_profiles: "always", and create a person profile for every user. This comes with an increase in costs
* Call `createPersonProfile()` when they know that the user is about to move from one site to the other, e.g. in an onClick handler. This might be difficult for no-code websites who don't have this level of control over their JS
* The user could keep track of the initial props themself, and call $set on the second site.

We could also solve this another way:
* Store the initial person info in the cookie instead. Cons: we'd just have to be wary of the 4k limit for cookies
* Add a way to automatically create person profiles when a link is clicked to a specific external site. Cons: this wouldn't work if they transferred to the site a different way, not through clicking a link
* Grab the person properties from the first event when an anon user is upgrade to having a person profile. Cons: this would be a huge infra challenge, as querying a single event from clickhouse during ingestion is a non-starter. I'm not convinced that this would be cheaper than just enabling person_profiles: "always"

**Comment by ItayElgazar** [comment]
Hi there,

(I think) I am facing the same problem, but on my end it's slightly different - since Google has blocked my website when logging in from Instagram, I need to open the app in Google Chrome / Safari instead of the facebook/instagram default browser. I am seeing a pattern where identified users have no `referrer` or `fbc` (facebook id). Do you think it is related? all identified usuers are categorized as direct referral.

**Comment by robbie-c** [comment]
Hey @ItayElgazar - could you open a ticket through our support system? That way I'll have more information to debug what's going on. It doesn't sound like it's definitely the same problem, so it'd be good to have that info to make sure
