### ISSUE TITLE
Cookie warning on Chrome

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog-js#17]
![image](https://user-images.githubusercontent.com/1727427/79437739-83d33600-7fca-11ea-97e9-6b4803450698.png)

This happens if you're logged into posthog and then go to your own site. This might affect our ability to do things like https://github.com/PostHog/posthog/issues/289

**Comment by mariusandra** [comment]
This is resolved. The "ph_*" cookie is now set with `Secure`.

![image](https://user-images.githubusercontent.com/53387/89776136-93423600-db09-11ea-88d5-624e60a1053d.png)
