### ISSUE TITLE
Retry Requests

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog-js#199]
Currently the [iOS](https://github.com/PostHog/posthog-ios/blob/543999884ea68330c7c80df18b33a3d5e3d21799/PostHog/Classes/Internal/PHGPostHogIntegration.m#L499) and [Android](https://github.com/PostHog/posthog-android/blob/master/posthog/src/main/java/com/posthog/android/PostHogIntegration.java#L358) libraries retry sending events in case the connection goes down. 

The JS library does not. It should have basic retrying capabilities to not lose events in shaky conditions.

*Context: Asked for in the PostHog users' Slack*

**Comment by yakkomajuri** [comment]
Done! cc @jeduden @aopetrov86
