### ISSUE TITLE
Idea: ability to change PostHog URL for Sentry event tag

### ISSUE THREAD

**Issue by MrSaints** [PostHog/posthog-js#206]
When using the PostHog integration with Sentry, it automatically includes a tag with a link to the PostHog user, e.g. `PostHog-URL: https://my-posthog.my-posthog.com/person/123abc`.

The PostHog URL is based on the `api_host`, https://github.com/PostHog/posthog-js/blob/93cb611c2da6cbed0acd70465df0d7db4f75db0b/src/posthog-core.js#L1356

We run a slightly unique PostHog set-up in that we have two different routes (or rather, hostnames). A private PostHog hostname, and a public PostHog hostname. All paths in the former are only accessible internally, and in the latter, only ingestion paths are accessible externally. We could get into semantics of why this is the case (e.g. why not protect specific paths versus. whole hostnames), but frankly, the gist of it is that it is easier.

Because of this unique set-up, the `PostHog-URL` set in Sentry is the hostname of our public PostHog.
I am wondering if we can consider allowing the base URL to be changed as part of the integration, 

```
PostHogLib.prototype.sentry_integration = function (_posthog, organization, projectId, prefix) {
```

Or would that be unnecessary complexity?

**Comment by alp82** [comment]
I have the same problem.

**Comment by Renaud009** [comment]
We are having same problem, any workaround for this without forking?
This issue should be re-opened.
