### ISSUE TITLE
InnerText censoring option

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog-js#210]
## Is your feature request related to a problem?

As a business, we have sensitive information on our platform that we cannot send to other platforms.

## Describe the solution you'd like

An option to turn off innerText collection globally in autocapture. We found that Pendo and Heap have this option.

It would also be nice to disable collection of certain attributes i.e.

```
...
disableInnerText: true,
disableAttributes: ["data-order-value"]
...
```

## Describe alternatives you've considered

The existing censoring tools you offer, but as our platform is very large, we'd need to invest time in finding the elements and adding the class to them.

## Additional context

We had a demo with James / Yakko (MentionMe).

#### *Thank you* for your feature request – we love each and every one!

**Comment by Twixes** [comment]
Hey! Moved this issue to posthog-js, as this should be a `posthog.init()` option.

**Comment by yakkomajuri** [comment]
This is essentially done, I just need to finish #209 but fell ill at the end of last week

**Comment by yakkomajuri** [comment]
Done and merged! #209

**Comment by joesaunderson** [comment]
Awesome, thanks! 

Do you have some docs on how we'd use this? Is it an option when adding the tag?

**Comment by lharress** [comment]
Looks like it was added as a `mask_all_text` option on the `init` call? If we enable `mask_all_text` will we also need to tweak the `session_recording` `rrweb` options? or will `mask_all_text` prevent `textContent` tracking across the board for the JS API (unless we track something manually and pass sensitive information)

**Comment by yakkomajuri** [comment]
Sorry for the delay here.

Docs are coming later today, but yes, you pass this to `init`.  `mask_all_text` only works for PostHog autocapture, `rrweb` doesn't have an option to do this natively unfortunately
