### ISSUE TITLE
Session recording enable/disable method?

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog-js#214]
Wondering if there's any opposition to exposing methods for enabling/disabling session recording on a per user basis?

Analogous to `opt_out_capturing`, but more specific.

A lot of users ask about having session recording on for a specific cohort only, and while it seems we want to build some of this functionality natively into the PostHog UI, if we expose a method to flip session recording on/off, users can:

1. Write their own logic to handle who has session recording on or not
2. Even better, use PostHog feature flags for this

This is somewhat doable now, but in very hacky ways.

**Comment by yakkomajuri** [comment]
cc @macobo

**Comment by macobo** [comment]
Sounds fair. I do think the 
>while it seems we want to build some of this functionality natively into the PostHog UI
Is easier for users and for us to manage long-term and isn't really hard technically - just needs some focus to get the feature out. I'm sort of far from the product right now though.

**Comment by yakkomajuri** [comment]
Yup I'm aware that you are - Hence if I put a method up to do this I can just do a tutorial on using feature flags for this
