### ISSUE TITLE
Feature flags not available if no auto-capture active without manual `reloadFeatureFlags`

### ISSUE THREAD

**Issue by IgnusG** [PostHog/posthog-js#218]
Calling `.init({  autocapture: false, capture_pageview: false })` will not create any requests to the server but thus also not retrieve any feature flags. The method `onFeatureFlags` then hangs indefinitely which is counter-intuitive.

Calling `reloadFeatureFlags` manually after init solves this (but due to #217 requires using `// @ts-expect-error` or `posthog.featureFlags.reloadFeatureFlags()`).

If this is desired behaviour, I would at least suggest mentioning this in the docs as a general reminder.

**Comment by macobo** [comment]
There's an in-progress PR fixing this - https://github.com/PostHog/posthog-js/pull/212. Hopefully will manage to get it in soon! :)

**Comment by yakkomajuri** [comment]
Done on #212
