### ISSUE TITLE
Reload modules when changing config (set_config)

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog-js#220]
We allow changing PostHog's config settings via `.set_config()`, however when settings change we don't necessarily reload the relevant modules. This particularly came from a user trying to enable session recording & autocapture in specific pages. They would try to update PostHog's config on the fly based on the current URL, but the modules don't get reloaded, so effectively changing the config doesn't work.

Related to #214

**Comment by jwei98** [comment]
Also having this issue! Trying to use `.set_config({ autocapture })` to toggle whether we auto-capture on certain url's

**Comment by pauldambra** [comment]
i've got session recording tests that assert this does work now
