### ISSUE TITLE
User request: Improve Next integration

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog-js#230]
## Is your feature request related to a problem?

https://twitter.com/ksaitor/status/1394603262158852099

## Describe the solution you'd like

Would be great to:
- Better support for SSR. Especially fallback for posthog.isFeatureEnabled() during SSR.
- Dynamic loading / smaller bundle size.

**Comment by mariusandra** [comment]
Moved from `posthog` to `posthog-js`

**Comment by lharries** [comment]
We now offer a React provider, useful hooks and a comprehensive guide on how to use PostHog with client side and server side react: https://posthog.com/docs/integrate/third-party/next-js
