### ISSUE TITLE
Capture viewport height and width automatically

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog-js#245]
In additional to $screen_height and $screen_width, let's track two more fields:
- $viewport_height
- $viewport_width

That are based off of `window.innerHeight` and `window.innerWidth` respectively

[Context](https://github.com/PostHog/product-internal/issues/70)

**Comment by corywatilo** [comment]
One question that will come up: is this session-level or sent with each event?

Seems excessive to track per event, but I could see it potentially being more useful. (It's plausible it can change, especially if the use case is trying to understand if users are adjusting to solve a UI issue.)

**Comment by kpthatsme** [comment]
This charts are based on total page views, so per-event.
