### ISSUE TITLE
Cookie name includes invalid characters which breaks .Net applications

### ISSUE THREAD

**Issue by a-teece** [PostHog/posthog-js#249]
The persistence cookie created by posthog often includes token separator characters which is not valid.
As per RFC 6265 a cookie name must be a valid "token" - [rfc6265#section-4.1.1](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.1)
And as per RFC 2616 a token can be any character except control characters and ( ) < > @ , ; : \ " / [ ] ? = { } [space] [tab]
[rfc2616#section-2.2](https://datatracker.ietf.org/doc/html/rfc2616#section-2.2)

As you can see from my sample cookie below the cookie name includes / and = both of which are forbidden: "ph_7KO4s0T55Ao2LarLN3QmFdJpluxT2uKoPH9i825TmPm/2wdGZjlKeKul7PlBI2cq5UfsQgV/WqOraybf0MEMCA==_posthog"

Combine this with the fact that when .Net processes cookies [if any 1 cookie is invalid then 0 cookies are processed](https://github.com/aspnet/AspNetWebStack/issues/118) and you can see that the inclusion of PostHog on a website where requests are made to a .net API using cookies for authentication (or other purposes) results in no cookies being available to the .net code. This isn't really a .net bug though as posthog is not obeying RFCs for naming cookies.

This is a P1 for us and we have been forced to remove posthog from our product until resolved. This has even broken other applications in our domain because the cookie is cross-site. So any .net application on the same domain is broken. Even after disabling posthog we now have to communicate with end users to clear cache to remove the invalid cookie. A pretty big issue!

We are aware that localstorage persistence is an option but if iFrames come into play (which we may not be in control of) it will fall back to cookies so don't consider this safe.

We are also aware that a "persistence name" can be set but can't find documentation on how "unique" this must be? Should it be unique per user, per instance of our app, per site, etc. We host multiple unique instances of our site on the same domain, sometimes on the same host.

**Comment by yakkomajuri** [comment]
Thanks for reporting. This is something that relates to token generation on the https://github.com/PostHog/posthog side. Two solutions I see here:

1. Prevent tokens from being generated on the `posthog` side that would be invalid cookies
2. Keep token gen the same but have `posthog-js` clean the token for invalid chars when setting the cookie.

1 wouldn't solve your issue "retroactively" (i.e. you'd need to generate a new token), but 2 would. 1 might be worth it anyway so we could actually do both.

**Comment by yakkomajuri** [comment]
For posterity, our teams communicated on Slack and the issue was fixed by regenerating the project token. 

We'll be adding a fix in so that this never happens again.

**Comment by Twixes** [comment]
As far as I understand, this has been solved with https://github.com/PostHog/posthog-js/pull/250
