### ISSUE TITLE
Posthog possibly crashed website on load, on old chrome v64

### ISSUE THREAD

**Issue by Amoodaa** [PostHog/posthog-js#256]
Sentry report, https://sentry.io/share/issue/b0e7d5f7ae354621b42202b6965375dc/
we started getting this just recently and the error message isnt the most useful

**Comment by Amoodaa** [comment]
Another incident of rrweb breaking the app
https://sentry.io/share/issue/3965a976c001457fb0280cb00b4ef544/
We use sentry and posthog, but only posthog records.

**Comment by larskoe** [comment]
@yakkomajuri We are too experiencing this issue. Here is the sentry issue: https://sentry.io/share/issue/cec9602b0f074896a2964acd7791a335/

**Comment by yakkomajuri** [comment]
Hey @larskoe @Amoodaa are you sure this broke things on load? 

We only use sendBeacon as a last resort if to send the data over.

Does this also happen often? Is there any more context you can share?

Nevertheless, I'm adding a bandaid in #337.

**Comment by larskoe** [comment]
@yakkomajuri It is happening quite frequently and putting noise in sentry. 

From what I can gather is that all of these events are on Chrome with a version of `80.0.3987` or less , so an older version of Chrome and they all seem to be coming from windows 10.  

Not sure if @Amoodaa has anything to add.

**Comment by yakkomajuri** [comment]
A new version is coming out now. Check if the problem persists after that! 

#337

**Comment by larskoe** [comment]
Thank you @yakkomajuri! I'll update this ticket if it still persists or not.
