### ISSUE TITLE
Error during load: this.parseDecideResponse is not a function

### ISSUE THREAD

**Issue by fergusleahytab** [PostHog/posthog-js#257]
We're loading posthog early in the page and did not wait for document ready. It looks like the code which tries to handle this situation fails when trying to call `this.parseDecideResponse`. 

Could it be because it's not an arrow func which binds `this`?

Here's our sentry backtrace.
https://sentry.io/share/issue/29c8fadd6ab34c509b128e8e100ee466/

**Comment by macobo** [comment]
You're 100% correct. Seems like this edge case has gone untested. Thanks for the great bug report, put a PR up!

**Comment by fergusleahytab** [comment]
Awesome! A tricksy edge case. Thanks for the pr fix.

**Comment by macobo** [comment]
This is now fixed with 1.12.2, thanks for the report!
