### ISSUE TITLE
crash in _captureMetrics if init is skipped in during development

### ISSUE THREAD

**Issue by skabbes** [PostHog/posthog-js#281]
**Context**
I am using PostHog within the Gatsby framework.  I am _not_ using the snippet installation, but instead importing as a module.

posthog-js version: 1.13.7
Browser: Chrome Version 92.0.4515.131 (Official Build) (x86_64)

**Problem**
In development, I skip `posthog.init` on localhost (as the [docs](https://posthog.com/docs/integrate/client/js) imply you can), but I still would like to sprinkle calls to `posthog.capture` throughout the code.  When I do call posthog.capture, I get an error, attached below - implying there is an uninitialized variable [this._captureMetrics](https://github.com/PostHog/posthog-js/blob/a6960bbdf252de2b93347dbcf196a686e5132747/src/posthog-core.js#L534)

![image](https://user-images.githubusercontent.com/592178/132705630-ab0aad6a-7c0f-4d93-b463-0a1f6a6dd87d.png)

**What I expected to happen**
I didn't expect `posthog.capture` to fail when I called it without initializing, I expected it to be a noop essenitally. Which would allow me to write succinct code for custom events.

```javascript
// I expected to be able to write code like this
const onVeryImportantClick = () => {
  posthog.capture('important-event', { very: 'important', data: true });
};

// not like this
const onVeryImportantClick = () => {
  if (some.config.someehwere.posthogEnabled) {
    posthog.capture('important-event', { very: 'important', data: true });
  }
};
```

Fixing the issue doesn't seem to be a big deal, but I'm not sure if not conceptually understanding posthog incorrectly, didn't understand the docs, or if this is a legitimate bug.  If the latter, I am more than happy to fix it.  Just looking for a project maintainer to give a little bit of guidance.

**Comment by skabbes** [comment]
I forgot to add the complete code for posthog initialization:

```javascript
/// gatsby-browser.js
import posthog from 'posthog-js';
import './src/styles/global.css';

const posthogEnabled = !(window.location.hostname === '127.0.0.1' || window.location.hostname === 'localhost');

export function onClientEntry() {
  if (posthogEnabled) {
    posthog.init("XXX", {
      api_host: 'https://app.posthog.com',
      autocapture: true,
      // pageviews will automatically be captured in `onRouteUpdate`
      capture_pageview: false,
    });
  }
}

export function onRouteUpdate() {
  if (posthogEnabled) {
    posthog.capture('$pageview')
  }
}
```

**Comment by timgl** [comment]
@skabbes Thanks for the report, this is definitely a bug. Calling capture without init should indeed be a noop. Would be awesome if you could find some time to put in a fix, we'll send you some merch as a thank you :)

**Comment by skabbes** [comment]
I repo'd in a test, and fixed it [here](https://github.com/PostHog/posthog-js/pull/282).  If you give any guidance for which other methods you'd like to noop, I can apply the same solution and update the PR (`identify` or  `alias` maybe?)
