### ISSUE TITLE
Add Sentry DSN for posthog-js configured to send to cloud

### ISSUE THREAD

**Issue by fuziontech** [PostHog/posthog-js#290]
This would be great to monitor if we are dropping events because of a few reasons:
- Issue with network between the client and cloudflare (cloudflare down or cloudflare not working in some geo)
- We push a breaking change to posthog-js we would want to know that the issue is happening.

We would want to scope this to just posthog-js instances configured to push events to app.posthog.com because there would be a lot of potential noise with on prem setups as well as data that customers would not want to share with cloud if they have an on prem deployment

**Comment by pauldambra** [comment]
example log here: https://sentry.io/organizations/posthog2/issues/2682143059/?project=5981339&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox

**Comment by pauldambra** [comment]
We now have an alert in sentry posthog2 that fires based on whether we're receiving status 502 https://sentry.io/organizations/posthog2/alerts/rules/details/33682/
