### ISSUE TITLE
How to use posthog-js within a Chrome Extension

### ISSUE THREAD

**Issue by leggetter** [PostHog/posthog-js#297]
This is an issue that I'll briefly leave open but will likely close after a week or so. The purpose of this issue is to:

1. Ensure there is a public asset with "posthog-js" and "Chrome Extension" to ensure others find a dedicated resource
2. Capture some feedback from the community and share it with others
3. Have a resource to refer to when we consider adding an official guide to the [PostHog integration docs](https://posthog.com/docs/integrate).

From a [discussion within the PostHog Community Slack](https://posthogusers.slack.com/archives/C01FKPGG5U6/p1618009615062200):

> incase anyone searches "chrome extension" in this slack in the future. So we found didn't need to use npm version in the end (deliberate choice since we decided to avoid using any third-party packages in our app to keep it lean) - instead we just added posthog.min.js to our scripts folder,  added "https://app.posthog.com/*" in permissions in manifest, then we have an init JS function which gets called when html template is loaded, and in that init function we call posthog.init('<KEY>', {api_host: 'https://app.posthog.com'}); and Voila! now we can add posthog.capture('anything_we_like'); anywhere in our other scripts we import.

If anyone has any more information on how they've used posthog-js within a Chrome Extension, please share it as a comment.

**Comment by obezzad** [comment]
Any updates?

**Comment by pauldambra** [comment]
there are docs for this now https://posthog.com/docs/advanced/browser-extension
