### ISSUE TITLE
Recording screen breaks with Apple Devices

### ISSUE THREAD

**Issue by wundo** [PostHog/posthog-js#309]
<img width="832" alt="Screen Shot 2021-10-04 at 13 43 24" src="https://user-images.githubusercontent.com/113942/135890906-8c2cffd1-c2d5-4f2a-b88a-e9532dc981be.png">

**Comment by alexkim205** [comment]
Hey @wundo, thanks for filing this bug! It's a bit difficult to see where that line is coming from in the screenshot. Would you be able to paste the trace stack here?

**Comment by wundo** [comment]
Looks like the error is on line 379 of https://app.posthog.com/src/record/observer.ts
