### ISSUE TITLE
User shown as unidentified even though it has all attributes from $identify

### ISSUE THREAD

**Issue by thomasgrastein** [PostHog/posthog-js#319]
Hello fellas! I've been noticing that when users sign out (posthog.reset() is called), and signs in (calling $identify with new uid) to a new user that has not been identified before, that new user will be shown as unidentified in PostHog, even though it has all the $set attributes from the identify call.

We are self-hosted and currently have persistence set to localstorage.

![Issue](https://i.imgur.com/wiJaU0n.jpg)

Edit: Actually we are using posthog cloud for development, and self-hosted for production. But I guess this is irrelevant as the issue is probably with posthog-js.

**Comment by vintersnow** [comment]
Same issue here. 
I create two accounts to test posthog and the first one has been identified correctly but the second one doesn't. There is one "unidentified user" with the ID I have set and many "unidentified users" with generated ID (a new person is created whenever I signed out and signed in)
I am using posthog cloud.

**Comment by rameshlohala** [comment]
Check this out. https://github.com/PostHog/posthog/issues/7351
I think the issue has been resolved and will be include in the next patch soon.
