### ISSUE TITLE
Not all pageviews/clicks captured

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog-js#32]
A user has reported they're not seeing all clicks appearing as expected.
![image](https://user-images.githubusercontent.com/1727427/82803185-fd86fb00-9e77-11ea-8faa-4f38246fea60.png)

While trying to reproduce I had the opposite problem where all the clicks were sent but not all the pageviews
![image](https://user-images.githubusercontent.com/1727427/82803335-3de67900-9e78-11ea-95f5-b16b63c1fa0d.png)

2 things happen: when we click, I think we wait 300 ms to try to send that click to the server before sending the user on. Depending on where the user is, 300ms might not be enough, or our server might be too slow.

The second thing is we batch requests, which might be playing havoc.

**Comment by mariusandra** [comment]
@timgl I've been looking into it, but I find it very hard to reproduce. How did you manage to even get the state where there were missed pageviews? 

Anyone else reading this: if you have any clues as to when and how this is happening, please chime in!

**Comment by mariusandra** [comment]
One theory I can propose is that the JS is working fine, yet somehow the backend loses events for whatever reasons.

**Comment by timgl** [comment]
Looks fixed with https://github.com/PostHog/posthog/pull/874

**Comment by mariusandra** [comment]
I will close this as the issue of randomly missing events seems to have gone away.
