### ISSUE TITLE
Session recording stops after calling the "reset" method

### ISSUE THREAD

**Issue by vlad-webdev** [PostHog/posthog-js#321]
Hi.
My app is a SPA, all users are working with the same page on my device, one at a time, one by one, without reloading the page between their sessions. 
But I have noticed a problem. When the first user logs out (my app is calling posthog.reset()), the sessions of the next users are not recorded.
While debugging in Chrome devtools, I see that after calling posthog.reset(), requests with payload from the page continue to be sent to the service, but no session records appear in my dashboard, although subsequent users continue to login (with posthog.identify()) and logs out (with posthog.reset()). 
The recording resumes only after manually reloading the page, but again, the recording only goes for the first user, until the next call to posthog.reset().

I am using the latest posthog-js lib (v1.14.4). The posthog instance is initialized with the following settings:
```
{
    api_host: ...,
    autocapture: false,
    capture_pageview: false,
    disable_session_recording: false,
    disable_cookie: true,
    loaded: (posthogInstance) => {
        ...
    },
}
```
Calling posthog.startSessionRecording after posthog.reset also has no effect.

**Comment by rcmarron** [comment]
Great, glad that PR fixes it! Should get it merged in soon.
