### ISSUE TITLE
/decide endpoint gets called twice

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog-js#339]
On a normal pageload on app.posthog.com, /decide endpoint gets called twice in a row.

I believe it's because:
1. We call /decide immediately on boot
2. We call /decide on reloadFeatureFlags that happens after `.identify()`

This causes extra load and traffic in an unneeded way

**Comment by macobo** [comment]
Related open question: We reload flags immediately after we change identity _or_ props. 

Reloading as identity changes makes sense. However for props:
- The $identify or properties setting message gets put into a queue in posthog-js
- Once it hits out servers it will get put into another queue
- Only after some latency will plugin server pick it up and process it

All this means is that user property changes won't be reflected in a new /decide response that's made immediately after `reloadFeatureFlags`.

**Comment by patricsteiner** [comment]
Is this issue rly fixed? It still happens to me... Without `identify()`, everything works as expected, 1 call to /decide and good. But whenever `identify()` is called, another call to /decide is fired.

**Comment by neilkakkar** [comment]
Hey @patricsteiner , this is by design, as when you call identify the identity changes.

If you always call identify right after load, then you can pass in the `advanced_disable_feature_flags_on_first_load` setting, which will ensure no flags are loaded on first call to decide, effectively making things much faster.

**Comment by patricsteiner** [comment]
@neilkakkar Oh, I didn't know that, thank you very much! :)
