### ISSUE TITLE
Toolbar sets debug mode true when logged in to PostHog

### ISSUE THREAD

**Issue by dan-dr** [PostHog/posthog-js#356]
Not sure, but since upgrading from `1.8.5` to `1.17.1`, we began to get posthog console logs in production:
`PostHog.js send {event: '$snapshot', properties: {…}}`

It's spamming our consoles - only for those of us that are logged in to the posthog instance.
I suspect the toolbar is at fault (sets config.debug true when authenticated):
https://github.com/PostHog/posthog-js/blob/master/src/extensions/toolbar.js#L22

Any way to disable it without disabling the toolbar?

**Comment by mariusandra** [comment]
That's a nice find, thanks for reporting! I have removed the line, and the new version should be live shortly. Please report back if that fixes the issue.

**Comment by dan-dr** [comment]
No problem! thanks for the quick fix :heart: 

Honestly kinda shocked no one complained :laughing:  from what I can tell that line has been there for a few months
