### ISSUE TITLE
Posthog throws an error when user logs in to the platform

### ISSUE THREAD

**Issue by wamujlb** [PostHog/posthog-js#393]
First of all I would like to say that this is a nice product. Thank you a lot. 

Regarding the issue: 

Posthog throws an error when user logs in to the platform. Error is thrown by the `posthog.capture` method. Here is the error:

```js
Uncaught TypeError: Cannot add property Symbol(__deepCircularCopyInProgress__), object is not extensible
    at deepCircularCopy (es.js:1192:1)
    at es.js:1206:1
    at Object._.each (es.js:1013:1)
    at deepCircularCopy (es.js:1204:1)
    at es.js:1206:1
    at Object._.each (es.js:1013:1)
    at deepCircularCopy (es.js:1204:1)
    at Object._.copyAndTruncateStrings (es.js:1218:1)
    at PostHogLib.<anonymous> (es.js:6226:1)
    at PostHogLib.capture (es.js:2898:1)
```
UPD:
I think it's something to do with the `Object.preventExtensions()`. Maybe we can check if the `Object.isExtensible()` before adding the `__deepCircularCopyInProgress__` property.

![Screenshot 2022-05-09 at 15 43 41](https://user-images.githubusercontent.com/14905044/167423896-5db1bfc2-d67f-48ed-a15b-3589f1fe2b94.png)

**Comment by AnandChowdhary** [comment]
I can reproduce this!

<img width="926" alt="CleanShot 2022-05-24 at 10 12 40@2x" src="https://user-images.githubusercontent.com/2841780/169982922-a510a23f-f54e-46e1-beb0-92e9023156dc.png">
