### ISSUE TITLE
initial_referrer poor interaction with posthog backend

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog-js#419]
## Bug description

Will be calling out a 2 different problems:

#### (1) `initial_referrer` is `set` (not `set_once`)

If someone calls `people.set` in posthog-js, then `initial_referrer` value is sent as `set` (code: https://github.com/PostHog/posthog-js/blob/00171cddfebc54a507f9edfc79974592b9e7a6ee/src/posthog-people.js#L51). Imagine `people.set` is called on the third user session, which means we'll be setting `initial_referrer` based on the initial referrer during this session (but it should be based on the person's first session).

In other events it's the same problem: Posthog-js sends `$initial_referrer` as a `$set` property, because we register it from here https://github.com/PostHog/posthog-js/blob/19a97b1755351d2934ef08b75f4018137e52c874/src/posthog-persistence.js#L201
and later properties get added to the event. 

There's an on-hold project for enabling any order ingestion. For that we'd make person property merging use timestamp and operation (set/set_once) to determine which property value should be used on conflict (currently we just use the identified person's values, which helps here as we won't be overriding `initial_referrer` in later sessions from identify due to merge, though we still do override because it's `set` also in the identify event).

#### (2) `initial_referrer` is handled differently from `initial_current_url`

Note: This applies to `initial_current_url` and everything else in https://github.com/PostHog/posthog/blob/ebfc8251a756470a10ddecc1913b356dbc0f30f0/plugin-server/src/utils/db/utils.ts#L52 too. 
This is a problem because the source of initial URL and referrer can now differ, but we'd assume initial URL and initial referrer to be from the same moment. Even if they are not truly initial due to how we do things they should be from the same moment. It would be weird to see `initial_url=myapp.com/fbclid=12345` i.e. FB and `initial_referrer=google`.

Note that in plugin server we have a function, that adds properties to person https://github.com/PostHog/posthog/blob/ebfc8251a756470a10ddecc1913b356dbc0f30f0/plugin-server/src/utils/db/utils.ts#L65
Specifically we try to set `browser`, `current_url`, `referrer` and others when the event properties contain those. Furthermore we also `set_once` their values with `initial_` prefix.

## How common is this problem?

To find examples:
1. Query in metabase `select * from events where team_id = 2 and _timestamp > today() and JSONExtractString(JSONExtractRaw(properties, '$set'), '$initial_referrer') = '$direct' limit 5` to see some examples of where we `set` the `initial_referrer`.
2. you'll see sth like
<img width="440" alt="Screen Shot 2022-07-04 at 16 24 43" src="https://user-images.githubusercontent.com/890921/177184041-ee4ca2fc-3401-4e4f-927c-a81d17d37a0f.png">

Based on our current logic for `set_once` (i.e. never override which is how we're doing the `initial_` for everything else) the `initial_*` per person should never change (except for alias calls, but let's ignore them for now as we don't use them for our team?).
I'm not sure of a good way to show how common the problem is, but for team 2 we can see a bit of the problem in CH on rows that aren't collapsed yet. Specifically we can see that `initial_current_url` doesn't change (https://metabase.posthog.net/question/362-initial-current-url-changes-per-person), but `initial_referrer` does (https://metabase.posthog.net/question/361-initial-referrer-changes-per-person)

## Additional context

https://posthog.slack.com/archives/C0374DA782U/p1656939422665609

## Proposed solution

Make `referrer` work the same way as `current_url` and [others](https://github.com/PostHog/posthog/blob/ebfc8251a756470a10ddecc1913b356dbc0f30f0/plugin-server/src/utils/db/utils.ts#L52) in posthog-js (that also means removing https://github.com/PostHog/posthog-js/blob/00171cddfebc54a507f9edfc79974592b9e7a6ee/src/posthog-people.js#L51 & https://github.com/PostHog/posthog-js/blob/5e92cfdb211f5616f4504358b99534eab380bb56/src/utils.js#L871 - neither of which we need as they should just all be set https://github.com/PostHog/posthog-js/blob/00171cddfebc54a507f9edfc79974592b9e7a6ee/src/utils.js#L826).

The more we handle complex logic on the server side the easier it will be for us to ship fixes as libraries getting updated has a much longer lag.

Potential problem with this proposal: 
1. events could arrive out of order and currently we don't look at timestamps when updating and `set_once` never updates. However this would make everything consistent from posthog-js perspective and we can/should follow-up on person property updates any order ingestion issue.
2. applies to all initial params: current url or referrer changes before we send the first event - seems unlikely as we send page views.

## Alternative

Make all the [initialParams](https://github.com/PostHog/posthog/blob/ebfc8251a756470a10ddecc1913b356dbc0f30f0/plugin-server/src/utils/db/utils.ts#L52) be stored in persistence and sent as `$set_once` to PostHog.

#### *Thank you* for your bug report – we love squashing them!

**Comment by tiina303** [comment]
cc @mariusandra  and @yakkomajuri  for your feedback/thoughts

**Comment by yakkomajuri** [comment]
Makes sense to me to just handle the same as current_url. Races shouldn't be as big of a deal as I wouldn't expect referrers to change _within_ a session. 

Feel free to put up a PR to do this

**Comment by timgl** [comment]
Given we did this, should we perhaps hide the property from the frontend if the property exists in the persons list? See https://twitter.com/rrmdp/status/1562085599615586304 for example of confusion from a user because of this

**Comment by tiina303** [comment]
Agreed - we should hide the `initial referrer` properties from the event properties in the UI. Not sure what's the best way to do that based how we populate those (introduce a blacklist?), happy to review PRs.
