### ISSUE TITLE
array.js uses a "define" that conflicts w/ (Adobe Commerce) Magento's requirejs

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog-js#433]
This issue is a blocker for a prospective customer, and we should fix if it doesn't add a lot of complexity. 

>"confirmed that their script (array.js) uses a "define" that conflicts w/ the one that Magento's requirejs uses. i’ve seen this a lot w/ third party scripts.
>
>we’ll need to load their script within the Magento codebase using requireJS
>(we can also let them know that their script won’t work with Adobe Commerce as-is)"
>
>Is there any alternative to this snippet that we can use? That will work more friendly with Magento 2 (Adobe Commerce), and can be used in GTM? It's a big problem having to do this outside of GTM; it might even be a deal breaker because this needs to track across different platforms, not just Magento.
>
>Our accounts in GTM allow us to segregate more efficiently for "Projects" that I will set up in PostHog. Losing that ability will be a significant disadvantage and much more challenging for us to keep track of since we have many things we track and manage in GTM for dozens of accounts.
>
>For example: This first project in PostHog tracks users across Magento and a React application (completely separate from Magento). This is set up in one account on GTM, and that is where this tag needs to live. If we can use GTM, we would have to install a PostHog connection into both applications, and there will likely be conflicts when the user journey crosses between applications.

**Comment by camerondeleone** [comment]
This was via DM, but I can provide more debugging info if someone wants to tackle this.

**Comment by camerondeleone** [comment]
@mariusandra can you take a look and let me know if this is something that we would fix or not?

**Comment by camerondeleone** [comment]
@timgl maybe you can advise too on this — is this something we should try to fix?

**Comment by timgl** [comment]
@camerondeleone I’ve been looking into this. Do you have the actual browser console errors this creates? Or some kind of description of what goes wrong? Hard to debug without!

**Comment by camerondeleone** [comment]
It looks like the toolbar is still using a define call that conflicts here. The problem was solved for capture (which is good, but the toolbar is still quite useful, since figuring out the unique selector by trial and error for all clickable elements is extremely painful).

> With tracking working again. I attempted to use the Toolbar to tag action events, and it breaks some parts of our sites. Specifically, the "decide" in the network loads gets hung up and attempts over and over forever. It looks like its attempting to do the define() when the Toolbar is enabled. Error: Mismatched anonymous define() module: function (storage){'use strict';return function(refreshUrl,formId,imageSource){return storage.post(refreshUrl,JSON.stringify({'formId':formId}),false).done(function(response){if(response.imgSrc){imageSource(response.imgSrc);}});};}
4 files 
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/56287180/186465259-ee311f5f-f6f5-4083-b22c-3d59eec7a744.png">
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/56287180/186465410-51953779-7f58-4bac-820e-2ba67d26bcaa.png">

**Comment by camerondeleone** [comment]
@yakkomajuri FYI if you have spare cycles this week (and feel well equipped to handle) this would be good since it's blocking a would-be paying customer.

**Comment by yakkomajuri** [comment]
@camerondeleone I've shipped a change that should solve this - can they try again?

**Comment by camerondeleone** [comment]
Thanks for giving it a go @yakkomajuri  — Looks like we still need a bit more tweaking here. Posting the issues [here](https://posthog.slack.com/archives/C02KGGDCA6Q/p1662481926048369) for context, but @timgl said he'd take it

**Comment by pauldambra** [comment]
confirmed fixed in linked slack channel
