### ISSUE TITLE
feat: Warn user when calling .init with an invalid token

### ISSUE THREAD

**Issue by danielthedifficult** [PostHog/posthog-js#440]
# Current behavior:

Calling .init with a token value that is undefined (as in my case, a .env var what wasn't being set properly), the JS PostHog library doesn't error, and doesn't call the loaded method/callback (fails silently)

# Expected behavior: 

Posthog library should warn if token or api_host URL parameters are undefined/null.

**Comment by pauldambra** [comment]
we do now do this https://github.com/PostHog/posthog-js/blob/d0aa984f9b8751e68baa08a979a3a66a3d4e8ee7/src/posthog-core.ts#L366-L371
