### ISSUE TITLE
Track global exceptions regardless of Sentry integration

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog-js#445]
# Problem
Currently we track an `$exception` event if the [Sentry Integration](https://github.com/PostHog/posthog-js/blob/master/src/extensions/sentry-integration.ts#L54) is active, hooking into some specific Sentry methods to get the exception info. This info is potentially useful for PostHog, regardless of the Sentry integration 

# Proposed solution
* Hook into global exception handling (similar to how Sentry does it) to capture `$exception` with some limited info
* If Sentry integration is enabled, then track it instead there with the extra sentry info

Related to https://github.com/PostHog/posthog/issues/3005

**Comment by macobo** [comment]
Note: Please make this configurable and default to off for at least existing installs as it could result in overages

**Comment by pauldambra** [comment]
i'll close this it's covered elsewhere
