### ISSUE TITLE
Bootstrapping breaks linking anonymous id with distinct id

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog-js#451]
**How to reproduce**

Our own signup flow has a user coming in with an anonymous id. Before, we'd call posthog.identify, which would link that anonymous id with the new distinct id. That behaviour has been broken since we started using bootstrap, as it immediately sets .

We basically need to add these two tests: (tried doing this but ran out of time!)
```
    it('calls capture when identity changes and old ID is anonymous', () => {
        given('deviceId', () => null)

        given('config', () => ({
            bootstrap: {
                distinctID: 'abcd',
            },
        }))

        expect(given.overrides.capture).toHaveBeenCalledWith(
            '$identify',
            {
                distinct_id: 'a-new-id',
                $anon_distinct_id: 'oldIdentity',
            },
            { $set: {}, $set_once: {} }
        )
        expect(given.overrides.people.set).not.toHaveBeenCalled()
        expect(given.overrides.featureFlags.setAnonymousDistinctId).toHaveBeenCalledWith('oldIdentity')
    })

    it("don't identify if the old id isn't anonymous", () => {
        given('deviceId', () => 'anonymous-id')

        given('config', () => ({
            bootstrap: {
                distinctID: 'abcd',
            },
        }))

        expect(given.overrides.capture).not.toHaveBeenCalled()
        expect(given.overrides.people.set).not.toHaveBeenCalled()
        expect(given.overrides.featureFlags.setAnonymousDistinctId).not.toHaveBeenCalled()
    })
```

**Comment by neilkakkar** [comment]
I'm away this week & half of next week, but initial hunch (not quite sure what's going wrong here): it seems to me that this is an issue with our implementation vs. the library itself, as these tests already exist.

Maybe we just shouldn't bootstrap any FFs when the identity isn't known here: https://github.com/PostHog/posthog/blob/master/posthog/utils.py#L337 - I guess I missed the fact that the users could be coming from `posthog.com`, and had an anonymous ID set there, which we're overriding here.

Hmm, although that does mean these anon users wouldn't have their flags be instantly available.
