### ISSUE TITLE
Autocapture and Capture Pageview disabled, but events are still getting tracked

### ISSUE THREAD

**Issue by goforbg** [PostHog/posthog-js#457]
Hi I'm using posthog-js on my chrome extension. 
A button is added for every page which has the init posthog function. 

I don't want events to be sent for every button click, but they're still being sent. 
I only want events in which I explicitly use the capture function. 

This is my current setup
`{
            api_host: `https://app.posthog.com`,
            autocapture: false,
            capture_pageview: false,
        }`

**Comment by pauldambra** [comment]
hey @goforbg i'm sorry we missed this!

that doesn't sound right, but we'd need more info... and I'm going to guess you're not patiently waiting nearly 2 years for our help still 🙈 

feel free to reopen if needed 💖
