### ISSUE TITLE
Cannot find namespace 'posthog'

### ISSUE THREAD

**Issue by jredl-va** [PostHog/posthog-js#466]
Within our monrepo (powered by nx) we bundle posthog js within a wrapping service that is exposed to our various frontend applications. This allows us to control the bootstrapping of posthog in a consistent fashion across all applications. 

I'm unable to install updates to posthog-js beyond posthog 1.25.0 for some unknown reason:

```
Error: libs/product-analytics/src/lib/product-analytics.service.ts:230:69 - error TS2503: Cannot find namespace 'posthog'.
```

Where posthog is imported like so:

```
import posthog from 'posthog-js';
```

Related technologies that power our frontends:

```
  typescript : 4.8.4
  rxjs: 6.6.7
  angular: 14.2.4
```

Any thoughts about how to resolve this?

**Comment by weyert** [comment]
Yeah, to have rewritten the library in TypeScript so the typings changed so you need to update your code to ensure to import it correctly

**Comment by jredl-va** [comment]
nm...I gotcha:

```
import { PostHog, Properties } from "posthog-js";
```
