### ISSUE TITLE
block all event / person data from user strings with `bot.html`

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog-js#472]
on heavily scraped sites, bots still generate junk data, increase event volumes, and result in persons with empty events. 

Some offenders visible in [this thread](https://posthog.slack.com/archives/C049839D57T/p1667242809643569)

We should block all autocapture events that match user agents above, or that contain `/bot.html`

**Comment by kamranayub** [comment]
I'm looking at a way to not capture events from Yandex bots from my Posthog. They have a [list of user agents](https://yandex.com/support/webmaster/robot-workings/check-yandex-robots.html), but it doesn't look like Posthog sends user-agent data. I'm thinking either I'll need to send a flag down from the server (e.g. `isBot`) or maybe posthog-js can handle this too.

**Comment by mariusandra** [comment]
We do have a list of bots that we block in posthog-js: https://github.com/PostHog/posthog-js/blob/master/src/utils.ts#L469-L509

Is there something we should add here?

**Comment by pauldambra** [comment]
we've significantly improved bot blocking since last comment... let's assume fixed
