### ISSUE TITLE
Illegal invocation from recorder.js

### ISSUE THREAD

**Issue by strewhella** [PostHog/posthog-js#473]
I'm seeing some crashes in our application originating from `recorder.js` when screen recording is enabled. The user in question has the user agent: `Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G950F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.4 Chrome/51.0.2704.106 Mobile Safari/537.36`

This appears to be version 1.32.4 of recorder.js according to our logs

<img width="739" alt="image" src="https://user-images.githubusercontent.com/8333989/202322228-a2fc9db2-c459-49e1-a769-2a56e7f645a0.png">

What can I do to mitigate this in the meantime apart from disabling screen recording altogether?

**Comment by pauldambra** [comment]
sorry we missed this @strewhella 💖 
i'm going to assume you don't have the problem any more and close this
