### ISSUE TITLE
Heatmap time selector does not reflect correct time period on element selector

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog-js#474]
Heatmaps - when you update the time selector, it doesn’t update it in the card itself - the data appears correct but the label persists on Last 7 days

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/56287180/202327808-8b7a90b2-6eb1-4967-9a3e-9fb987586cf1.png">

**Comment by pauldambra** [comment]
I don't know when in the last 18 months we fixed this... but we did
