### ISSUE TITLE
Improve NextJS Integration

### ISSUE THREAD

**Issue by lharries** [PostHog/posthog-js#492]
I was helping a user integrate NextJS, we several problems with the official nextjs tutorial

## Problems

When following the official implementation [Setup and tracking page views (automatically)](https://posthog.com/docs/integrate/third-party/next-js):
- The [next-use-posthog](https://www.npmjs.com/package/next-use-posthog) Github package recommended in the [official tutorial](https://posthog.com/docs/integrate/third-party/next-js) uses PostHog 1.16.0 which is quite far behind
- The Github package above is maintained by a third party and not by us (although we appreciate them making it!) which gives less ability to add first class nextjs support. It has over 3,000 downloads and climbing

When following the alternative official implementation [Setup and tracking page views (manually)](https://posthog.com/docs/integrate/third-party/next-js#setup-and-tracking-page-views-manually):
- Having `posthog.reset()` on a different page, often resulted in using seeing the error `Error: TypeError: Cannot read properties of undefined (reading 'props') `. This error is referenced here: https://github.com/PostHog/posthog-js/issues/323 and occurs because posthog.reset() runs before posthog initialized.
- The above problem also happens when feature flags are loaded before the product is initialized. And I suspect that feature flags won't work as expected with server side rendering

## Potential solutions

We might want to do multiple of these:

1. Update the existing next-use-posthog package to use the latest version of posthog-js
    - Draft PR here: https://github.com/Ismaaa/next-use-posthog/pull/8
2. Somehow get the npm package maintained by us and create an official fork. It has over 3,000 downloads a week and it's rising
3. Fix posthog.reset() by handling it the same way capture does - do a noop if it hasn't been initialized. However, this will likely result in engineers thinking that reset has been called when it hasn't if the library hasn't been initialized
    - Draft PR created here https://github.com/PostHog/posthog-js/pull/490 
4. Fix posthog.reset by recommending how to use posthog.reset properly in nextjs and react
5. Create guidance for how to use feature flags in nextjs. Should we have a react hook based implementation? And/or give guidance for how to use feature flags with server side rendering (lower priority)?

Feedback requested: what's the best way to tackle these problems?

**Comment by pjhul** [comment]
100% agree with what you mention here, and given how popular Next.js is I this this should definitely be a priority. I personally think creating our own wrapper is the best way to go, especially given how simple the current library is. 

Another library to take inspiration from is [next-plausible](https://github.com/4lejandrito/next-plausible). This implementation is particularly cool as it leverages Next.js built-in rewrites to give you proxying out-of-the-box.

**Comment by onurgenes** [comment]
Do you have any updates on this?

I can't integrate Experiments because of this error.

**Comment by lharries** [comment]
Hi @onurgenes, what's the error that you're getting? It seems to work if you wrap all the posthog calls in useEffect

**Comment by ivanagas** [comment]
Been trying to think about how to work on this, I think I will just do the obvious thing and write a big tutorial building a Next.js app then adding PostHog (and its features) to it. Other tutorials like this perform well, and we can pull snippets into more officially documentation in the future. 
https://github.com/PostHog/posthog.com/issues/5297

**Comment by lharries** [comment]
Closed with https://github.com/PostHog/posthog.com/pull/5399

We now have 1st class [React](https://posthog.com/docs/sdks/react) support and great support for [Next.js](https://posthog.com/docs/integrate/third-party/next-js)
