### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog-js#50]
We need a proper test suite for this library, including tests for all the new features.

**Comment by mariusandra** [comment]
A lot of tests are now in place, yet more tests should be added for `featureFlags` and batching. Possibly other things as well.

**Comment by mariusandra** [comment]
I spent more time than I'd like to admit to try to make tests for feature flags. However, the way this library is set up, it feels really hard to do. I've gotten to a point where I think it's easier to refactor/rewrite parts of the library itself instead of trying to hack some tests onto it.

To be continued...

**Comment by macobo** [comment]
Note: some of the newer code is now easier to test thanks to using less mocking and more di/given2/jest:

Examples:
- https://github.com/PostHog/posthog-js/blob/master/src/__tests__/extensions/toolbar.js
- https://github.com/PostHog/posthog-js/blob/master/src/__tests__/extensions/sessionrecording.js
- https://github.com/PostHog/posthog-js/blob/master/src/__tests__/extensions/sessionid.js
- https://github.com/PostHog/posthog-js/blob/master/src/__tests__/autocapture.js#L772-L864

That said, a lot of work still remains to be done here as well as introducing some sort of integration tests.

**Comment by macobo** [comment]
There is now an integration test suite which tests some functionality with a real browser.

@mariusandra will close this ticket for the moment as the original problem is solved. I think it's worth enforcing that new changes will have proper test coverage and we'll see what happens to the library.
