### ISSUE TITLE
Sentry types are not found with 1.39.5

### ISSUE THREAD

**Issue by arm1n** [PostHog/posthog-js#505]
When using latest version `1.39.5` it breaks with the following message from `tsc` as soon as I import `import posthog from 'posthog-js'`:

```
Cannot find module '@sentry/types' or its corresponding type declarations.
```

**Comment by pauldambra** [comment]
Hey @arm1n, we did make a change to move Sentry types to dev dependencies last week

https://github.com/PostHog/posthog-js/pull/504

@macobo so I don't end up undoing something by accident what was the motivation for that change?

**Comment by macobo** [comment]
Feel free to revert as it's causing problems. Someone was having issues including posthog-js with an older version of typescript but only not including sentry did not do the trick.

**Comment by n3tlify** [comment]
Thanks for taking care!

**Comment by arm1n** [comment]
Thanks for taking care!

**Comment by pauldambra** [comment]
Hey @arm1n 1.40.2 has been released now.

Does that work for you?
