### ISSUE TITLE
allow customization of shouldCaptureDomEvent / event targes?

### ISSUE THREAD

**Issue by rksm** [PostHog/posthog-js#51]
Is there a way to allow the user to customize what elements should be auto-captured? I'm having a code base with lots of `div.button` elements and would simply like to add elements if they include the `.button` class.

Alternatively, but to a lesser degree, the opposite of `ph-no-capture` would be helpful as well.

Thanks!

**Comment by mariusandra** [comment]
Hi @rksm - do all those `div.button` elements have `cursor:pointer` on them? If so, then starting with posthog-js version 1.2.3, they should be captured automatically.

**Comment by rksm** [comment]
Alright, sounds good, thank you!
