### ISSUE TITLE
Support fetch as alternative to XMLHttpRequest and sendBeacon

### ISSUE THREAD

**Issue by TimNZ** [PostHog/posthog-js#513]
Please add support for using native browser fetch() and the use of keepalive flag as an alternative to sendBeacon, configurable in .init() and .capture() options.

I'm trying to get client side send events to be almost block proof and send reliable, before reverting to routing throug my server side API if I have to [not a biggie if have to].

uBlock blanket blocks 'ping' method requests which is the method navigator.sendBeacon() uses.

Already using a custom domain and proxying through nginx to Posthog Cloud.

**Comment by pauldambra** [comment]
we do now support fetch
