### ISSUE TITLE
better handling for multiple end users on a single device

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog-js#527]
I'm relaying this secondhand so I might have some of the details off, but as I understand the issue:

- It is required to call `posthog.reset(true)` on logout in order to properly identify users on the next login. Otherwise, even though the `distinct_id` has been cleared, the `device_id` is still stored in the cookie, and that value is used on startup
- Normally when a user logs in fresh (for the first time on a device), an `identify` event is emitted (with the anon id if no value is provided on startup). 
- However, IF the `device_id` is still stored (because `reset` was called rather than `reset(true)`) no `identify` event is emitted. 

So, calling `reset(true)` is required. However

- This breaks cross domain tracking when it's attempted to run on a marketing site -> into a product (to add more clarification here if necessary)

Being discussed here https://posthog.slack.com/archives/C046YCXSZ2Q/p1675288018216639

**Comment by pauldambra** [comment]
See https://github.com/PostHog/posthog-js/issues/512

**Comment by pauldambra** [comment]
identify behaviour was fixed in #512 so no need to call `reset(true)` any more
