### ISSUE TITLE
posthog-js loaded via npm misses iOS Safari pageviews and events

### ISSUE THREAD

**Issue by brianjychan** [PostHog/posthog-js#53]
I found that loading posthog-js via npm would miss pageviews and events coming from my iOS Safari browser.

However, loading it via <script> instead seems to capture all events.

Other notes:
- Using Heroku deploy, no upgrades beyond default free

**Comment by SuperKruse** [comment]
Hey, 

It sounds like it is the same issue as https://github.com/PostHog/posthog-js/issues/66

A workaround should be to set `request_batching: false` when initializing posthog.

**Comment by mariusandra** [comment]
Hey! I think PR #69 fixed this in version `1.3.2`. Thus closing this issue.

@brianjychan can you confirm if this is the case in case this is still relevant for you? If not fixed, please reopen.
