### ISSUE TITLE
lint or test for usages of window that would break service workers

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog-js#547]
See https://github.com/PostHog/posthog-js/pull/541 and https://github.com/PostHog/posthog-js/pull/542

If used in a ServiceWorker we cannot guarantee that window is available. But it is easy to write code that assumes window is available.

We should protect ourselves from making that mistake

**Comment by chidg** [comment]
Hi @pauldambra,
Thanks for this. We are currently adapting an extension from manifest v2 to manifest v3 (which requires the use of a service worker), and finding that we will not be able to continue to use Posthog in the background script as yet, so appreciate this initiative. I hope you don't mind me adding a few pointers for things that will need to be updated if Posthog is to be functional in the service worker environment.

As a starting point, we notice a lot of errors originating in https://github.com/PostHog/posthog-js/blob/master/src/posthog-core.ts
Essentially any reference to `window` or `document` in that file which assumes the existence of particular properties will throw.

Another important limitation in Chrome extension manifest v3 is that `fetch` is now the only http method allowed in the extension. This means that `xhr` from https://github.com/PostHog/posthog-js/blob/master/src/send-request.ts will not work in the extension.

**Comment by benjackwhite** [comment]
Part 1 of this should be solved in the linked PR.
Part 2 (using fetch) is something that might need more follow up
