### ISSUE TITLE
TypeError undefined is not an object (evaluating 'e[Symbol.iterator]')

### ISSUE THREAD

**Issue by tonyxiao** [PostHog/posthog-js#560]
We are getting this inside our sentry pointing to posthog and we have no idea what it's about and are not able to reproduce it on dev machine. Do you guys have ideas?

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/696842/222127148-a3163170-e749-46a7-88cd-893d5e1ee0f0.png">

**Comment by tonyxiao** [comment]
FWIW the devices used were 

Mobile Safari 16.1  
Chrome Mobile iOS 110.0.5481

**Comment by yuvrajchaudhari03** [comment]
facing same isssue

[
![Screenshot 2023-03-01 at 5 44 15 PM](https://user-images.githubusercontent.com/52877982/222151655-865b2c8d-f093-4d9f-929e-8811a13615f4.png)

![Screenshot 2023-03-01 at 5 43 22 PM](https://user-images.githubusercontent.com/52877982/222151639-ba1ae327-6eb5-4d86-9d2b-e3650bcd5a17.png)
](url)

**Comment by Johannes-Berggren** [comment]
Same here!

**Comment by adrianwix** [comment]
Same here
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/37629556/227180881-f6b14c8c-a3f7-4567-a17b-5a0893b37c1d.png">

**Comment by yuvrajchaudhari03** [comment]
> facing same isssue
> 
> ![Screenshot 2023-03-01 at 5 44 15 PM](https://user-images.githubusercontent.com/52877982/222151655-865b2c8d-f093-4d9f-929e-8811a13615f4.png)
> 
> ![Screenshot 2023-03-01 at 5 43 22 PM](https://user-images.githubusercontent.com/52877982/222151639-ba1ae327-6eb5-4d86-9d2b-e3650bcd5a17.png)

reinstall posthog fixed this issue for me

**Comment by adrianwix** [comment]
I think this issue is already solved in the latest version and therefore could be closed

**Comment by Twixes** [comment]
Closing, but please reopen if you see this on a `posthog-js` version newer than 1.50.
