### ISSUE TITLE
This provider has already been initialized. You should only initialize it once at the root of your app.

### ISSUE THREAD

**Issue by whollacsek** [PostHog/posthog-js#568]
Hi I'm a first time user and I'm currently blocked as I got this error when following this guide https://posthog.com/tutorials/nextjs-supabase-signup-funnel 

Same issue when trying to run the example project: https://github.com/PostHog/posthog-js/tree/master/playground/nextjs

Seems like you have a logic issue, this condition is always true: https://github.com/PostHog/posthog-js/blob/75b35c22df0381bfe9b46b60190de7c24233cca5/react/src/context/PostHogProvider.tsx#L34

posthog-js version 1.50.4

Is there a workaround?

**Comment by neilkakkar** [comment]
cc: @lharries

**Comment by lharries** [comment]
Hi @whollacsek, that should be fixed here: https://github.com/PostHog/posthog-js/pull/566

Would you mind updating to 1.50.7?
