### ISSUE TITLE
Unifying code style – linting with Standard

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog-js#58]
Might be good to lint/fix all of the code to keep it all in the same style without wasting time on that personally. I really love [Standard](https://standardjs.com/) (based on ESLint) for this – basically Black for JS, zero tinkering. Would it be OK to add this?

**Comment by mariusandra** [comment]
Hey, love the initiative!

I guess it's best to use the same code style we use with `posthog`, which is just a simple [prettier](https://github.com/PostHog/posthog/blob/master/.prettierrc) config. 

I used standard in my previous project and loved it... however using vanilla prettier is a bit easier for all contributors. The only thing I miss with prettier is the space before the function params when it's defined (`function bla ()` vs `function bla()`) to clearly separate function definitions from invocations... but I got used to it by now :)
