### ISSUE TITLE
Deprecate `.people.set`

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog-js#580]
We have a method for setting properties via `posthog.people.set` which we document but is actually a relatively convoluted bit of code that from what I can see does two things:

1. Triggers an `$identify`-esque call (the eventual event landing in PostHog is $identify)
2. Checks for `save_referrer` config option  and saves it (not sure where this is used) - NOTE: This has been reported as sometimes erroring

It has a lot of very duplicated code to the rest of the core codebase.

## Proposal

1. Remove the existing implementation and simply alias it to `.identify` with the appropriate set/set_once options
2. Stop documenting it and instead document the standard flows (identify or capture with $set)
3. (Optional) Potentially add an ID-less identify such as `registerPersonProperties` which would map to identify with the existing distinctId and only trigger the identify call if the passed properties are different to any previous call.

**Comment by neilkakkar** [comment]
Seconded, further this ends up sending multiple identify requests when `identify()` itself calls `people.set` and `people.set_once`

**Comment by joepavitt** [comment]
Just wanted to check, is the best practice here in fact _just_ to call an `identify` event instead? Building out [Node-RED nodes](https://github.com/joepavitt/node-red-contrib-posthog) and just want to get an understanding of what coverage I need.

**Comment by benjackwhite** [comment]
Some good context from @tiina303 in this comment https://github.com/PostHog/posthog-js/pull/584#pullrequestreview-1370611979

There is a `$set` call which can be used instead which is more explicit than `identify` if you are really _only_ updating person properties.
