### ISSUE TITLE
Safari exception (cannot load script due to access control checks)

### ISSUE THREAD

**Issue by olliejm** [PostHog/posthog-js#589]
I'm seeing the following issue when we try to initialise posthog on safari:

```
XMLHttpRequest cannot load https://eu.posthog.com/e/?compression=gzip-js&ip=1&_=1679063940426&ver=1.51.2 due to access control checks.
```

This prevents our application from loading unless we totally disable posthog on safari

**Comment by pauldambra** [comment]
hey,

i can't reproduce this so I'll close it considering the age

but if folk can repro and want to reopen, please do!
