### ISSUE TITLE
Bad HTTP status: 0 

### ISSUE THREAD

**Issue by mukunpoudel123** [PostHog/posthog-js#591]
I am running into a situation where large number of sentry events are getting triggered with `Bad HTTP status: 0` . 
Configuration : current posthog-js version     : ^1.32.2
Below attached is sentry console: 
`message
Bad HTTP status: 0 
Error
18:07:42
xhr
POST https://app.posthog.com/s/?compression=gzip-js&ip=1&_=1679416637111&ver=1.39.0 [0]
Info
18:07:42
console
Enqueued failed request for retry in 24000
{
arguments: [
Enqueued failed request for retry in 24000
], 
logger: console
}
Warning
18:07:39
console
Bad HTTP status: 0 
{
arguments: [
Bad HTTP status: 0 
], 
logger: console
}
Error
18:07:39
xhr
POST https://app.posthog.com/s/?compression=gzip-js&ip=1&_=1679406851972&ver=1.39.0 [0]
`

**Comment by jeremyisatrecharm** [comment]
I am also seeing this and items like `Enqueued failed request for retry in 6000`

**Comment by NotJustClarkKent** [comment]
This seems to happen if the client is using an ad-blocker.

**Comment by jeremyisatrecharm** [comment]
I don't have an ad blocker.

**Comment by ErycM** [comment]
Same here.

**Comment by pauldambra** [comment]
http status 0 is 99.9999% an ad blocker or similar stopping the http connection

if someone can provide a reproduction that isn't an adblocker or a public site I can visit to check please reopen!
