### ISSUE TITLE
Unnecessary argument for useActiveFeatureFlags

### ISSUE THREAD

**Issue by calvinwoo** [PostHog/posthog-js#596]
The `useActiveFeatureFlags` React hook requires a `flag` argument, which doesn't appear to be used at all. https://github.com/PostHog/posthog-js/blob/master/react/src/hooks/useActiveFeatureFlags.ts#L4

Causes a type issue — quick workaround is just to supply a filler string.

**Comment by curtvict** [comment]
Agreed. This argument seems completely superfluous.

**Comment by curtvict** [comment]
I opened a PR for this https://github.com/PostHog/posthog-js/pull/599
