### ISSUE TITLE
SyntaxError in sessionrecording-utils.ts

### ISSUE THREAD

**Issue by curtvict** [PostHog/posthog-js#597]
I'm getting intermittent errors coming from: `../node_modules/posthog-js/src/extensions/sessionrecording-utils.ts`

```
SyntaxError: Expected ',' or '}' after property value in JSON at position 527507
```

Is anyone else seeing this?

**Comment by pauldambra** [comment]
This is probably related to the data img size probing which wasn't robust enough https://github.com/PostHog/posthog-js/pull/851
