### ISSUE TITLE
recorder v2 error in console from rrweb2

### ISSUE THREAD

**Issue by antoinerousseau** [PostHog/posthog-js#598]
using config:
```
session_recording: {
  inlineStylesheet: true, // otherwise older recordings get a 404 for the CSS file
  recorderVersion: "v2",
  // @ts-expect-error https://posthog.com/docs/session-replay/configure
  recordCanvas: true,
},
```
and `posthog-js` 1.51.5

I have this in the browser console sometimes, when clicking stuff like a checkbox label:

```
Uncaught TypeError: Cannot set property attributeName of #<MutationRecord> which has only a getter
    at processMutation (mutation.js:311:31)
    at Array.forEach (<anonymous>)
    at e.processMutations (mutation.js:95:23)
```

<img width="368" alt="Capture d’écran 2023-03-31 à 20 17 26" src="https://user-images.githubusercontent.com/160279/229199101-3e5ff4a7-c1ee-4905-8de1-01e4bb959850.png">

**Comment by pauldambra** [comment]
hey, sorry nobody replied here!

i'll close this since so much time has passed and we've changed a lot since march

but feel free to reply if it's still a problem for you (in which case the first questions will be: can you try the latest version and is the site public for us to investigate)
