### ISSUE TITLE
Modify the version bump action to post changelog to Github Releases

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog-js#610]
We already auto-generate the Changelog based on commit messages but we can improve this by posting the summary to a Github Release as well so that it is easier to see from the Releases page.

 
https://github.com/PostHog/posthog-js/blob/master/.github/workflows/label-version-bump.yml

**Comment by pauldambra** [comment]
this happens now https://github.com/PostHog/posthog-js/pull/1008
