### ISSUE TITLE
Limit session recordings with NextJs 

### ISSUE THREAD

**Issue by kylemorena** [PostHog/posthog-js#612]
Hello, 
I'd like to add this criteria: `currPath==="/new-page"`  on **Release condition**.
So it would start recording only if a user has been passed through `/new-page`, but I didnt found any similar condition. 
Is there any chance to do it? 
Here is my code:
**limit_session_recordings**
![image](https://user-images.githubusercontent.com/49655623/232508249-40cfcece-8e5f-45a7-9272-01155362a723.png)

```
posthog.onFeatureFlags(() => {
      if (posthog.isFeatureEnabled("limit_session_recordings")) {
        posthog.startSessionRecording();
      }
    });
```

**Comment by kylemorena** [comment]
> Say you have a `$current_url` property on your persons, you will now be able to do:
> 
> ```
> posthog.personProperties({$current_url: '/new-page'})
> ```
> 
> which will use this property for evaluating flags instead of what's stored in the database.
> 
> Should be live once this is merged: #613

Perfect, thank you so much for your support!

**Comment by neilkakkar** [comment]
Hey Kyle, this is released now, you can find the docs here: https://posthog.com/docs/libraries/js#overriding-server-properties - let me know if you face any issues :)

**Comment by kylemorena** [comment]
> Hey Kyle, this is released now, you can find the docs here: https://posthog.com/docs/libraries/js#overriding-server-properties - let me know if you face any issues :)

Hello @neilkakkar, I've tested it and seems like its working! ty!

**Comment by neilkakkar** [comment]
Perfect 🙌
