### ISSUE TITLE
"Cookieless tracking" still sends some cookies

### ISSUE THREAD

**Issue by vetalcore** [PostHog/posthog-js#614]
Based on https://posthog.com/tutorials/cookieless-tracking i'd expect that after setting `persistence: 'memory'` param i should not be able to see any kind of cookies attached to post hog capture events http calls.

**Actual outcome**
- is same as here https://posthog.com/questions/cookie-less-tracking-not-working.

**Expected outcome**
- no cookies are attached?

Full example:
```
posthog.init(PUBLIC_POSTHOG_KEY, {
      api_host: PUBLIC_POSTHOG_HOST,
      autocapture: false,
      disable_session_recording: true,
      capture_pageview: false,
      capture_pageleave: false,
      disable_persistence: true,
      disable_cookie: true,
      persistence: 'memory'
})
```

**Comment by BrunnerLivio** [comment]
Same issue here. I'd appreciate some transparency on this?

**Comment by neilkakkar** [comment]
curious, can you send the name of the cookies? It's possible you'll still have our cookies (`ph_STM...._posthog`), but not necessarily cookies for your posthog installation, which has your project key in the name

**Comment by BrunnerLivio** [comment]
@neilkakkar yup that's the cookie. Seems like some kind of encoded JSON is stored in there:
```
{"distinct_id":"Cw****","$sesid":[16***,"01*****",******]}
```
Is there some documentation why this Cookie is needed or is it possible to opt out of that?

**Comment by neilkakkar** [comment]
So, that's a cookie that applies to you, not your users. And it applies to you because you use posthog's app.

**Comment by BrunnerLivio** [comment]
@neilkakkar ahh okay all clear then, thanks for the clarification and quick response!

**Comment by neilkakkar** [comment]
Cool 👍 

@vetalcore let me know if your case is different, feel free to re-open if so
