### ISSUE TITLE
Properties set via `PostHog.identify` parameter `userPropertiesToSetOnce` are not passed to API

### ISSUE THREAD

**Issue by majgaard** [PostHog/posthog-js#615]
It is now clear to me that user properties set via `userPropertiesToSetOnce` on `PostHog.identify` are not respected.
The properties are passed to `PostHog.capture`, which does not seem to use the `$set_once` property for anything.

https://github.com/PostHog/posthog-js/blob/14f230a033c71d5379f26bc2ccb2c504971fe888/src/posthog-core.ts#L1216-L1223

On the lines below, `PostHog.capture` extracts the `$set` property from the passed `options` parameter, but ignores the `$set_once` property. 
https://github.com/PostHog/posthog-js/blob/14f230a033c71d5379f26bc2ccb2c504971fe888/src/posthog-core.ts#L848-L850

Later on the `options` parameter, which now includes `$set_once`, is passed onwards to the request functions as XHROptions, where they are not relevant.
https://github.com/PostHog/posthog-js/blob/14f230a033c71d5379f26bc2ccb2c504971fe888/src/posthog-core.ts#L871-L875

This feature was introduced with version 1.8.10 back in 2021, and I doubt it has ever worked. 
https://github.com/PostHog/posthog-js/blob/8237655d70cfe26c7845ac9ab72f726b50156513/CHANGELOG.md#L732-L737

If someone from the team can confirm that extending `PostHog.capture` to also extract `$set_once` from `options` is the desired fix, I am happy to submit a PR. However, it seems like the docs insist on calling `capture` with `$set_once` in the `properties` parameter (as shown below).
```js
posthog.capture('some event', { $set_once: { userProperty: 'value' } })
```

**Comment by hazzadous** [comment]
@majgaard I would go with copying what is happening with `$set` and pulling from the `options`, if only for consistency. It looks like we [normalize](https://github.com/PostHog/posthog/blob/master/plugin-server/src/utils/event.ts#L82:L82) such that either top level or within `properties` is used.

I've updated some tests/docs [here](https://github.com/PostHog/posthog/pull/15306/files) fwiw.

Ideally we'd use the http request as the testing boundary, but don't feel like you need to make that update 🙏
