### ISSUE TITLE
certain event property names result in empty events send to PostHog Cloud

### ISSUE THREAD

**Issue by SergNikitin** [PostHog/posthog-js#632]
*Thank you to everybody working on this project 💖*

## Bug description

When calling `.capture()`, it seems that certain property names always result in a completely unpredictable outcome. I'm not sure what's the source of this & what's the full list of these names, but I have observed that calling

```js
posthog.capture("myevent", {
    foo: "bar",
    length: 0 // this property turns event bad
})
```

Results in the following JSON being sent to PostHog Cloud:
```json
{ "event": "myevent", "properties": {}, "offset": <some number> },
```
Notice that the properties are *completely empty* - not even the PostHog's "internal"/"out of the box" properties like `distinct_id` are absent.
In turn, this makes PostHog respond with the following error:
```json
{"type": "validation_error", "code": "invalid_payload", "detail": "Invalid payload: All events must have the event field \"distinct_id\"!", "attr": null}
```

Based on my experiments, for an unknown reason a property named `length` triggers this outcome. Remove the property -- everything works smoothly. It doesn't matter how many other properties are present.

## How to reproduce

1. Run `posthog.capture()` with parameters similar to the above example
2. For a real example, see https://gist.github.com/SergNikitin/a4735e1a6ba248631eb8ab0d018c68c7 for a real network request which `posthog-js` sent from my web application (and a `curl` command that I happened to extract through Chrome Dev Tools)
7. Remove `length` property or rename to something else like `count` and see the error go away

**Comment by benjackwhite** [comment]
Hmmm this is likely due to some nastiness with JS objects. "length" is a pretty tricky beast as it affects all sorts of things like looping over properties...

Likely we need to add a test for this and see if there is a workaround...
