### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by j3ski-bioraptor** [PostHog/posthog-js#652]
This error was thrown inside the "_handle_queued_event" event handler. It seems to be related to serialising an object which is too large(?).

Is there a way to mitigate this, for example by limiting the queue size? I don't use much custome events, so I would assume this is related to some autocapture and/or screen recording. In fact the sentry-posthog integration points to a screen recording that is not found when I search for it at posthog.com

Posthog version: 1.51.2
Browser: Chrome 113.0.0
OS: Mac OS X >= 10.15.7

**Comment by pauldambra** [comment]
sorry nobody replied here... so much time has passed i'll assume this is resolved... please reopen if that's not true!
