### ISSUE TITLE
Maximum call stack size exceeded when working with Turbo

### ISSUE THREAD

**Issue by michael-yin** [PostHog/posthog-js#666]
I found posthog JS lib can not work with [hotwired/turbo](https://github.com/hotwired/turbo), which is a very popular frontend lib in  Rails community.

If I click some links to do page navigation, then I will get the "Maximum call stack size exceeded"

And I think there might be some conflict between [posthog-js](https://github.com/PostHog/posthog-js) and Turbo

<img width="1976" alt="Screen Shot 2023-06-01 at 3 21 12 PM" src="https://github.com/PostHog/posthog-js/assets/4366781/bf42688a-d26d-4d95-a7e0-1a39c3e449a4">

**Comment by gsumo** [comment]
I am having the same issue with HTMX

**Comment by hevans90** [comment]
This is a pretty prevalent issue with our next.js 13/turborepo setup, this happens ALL THE TIME:

<img width="1310" alt="image" src="https://github.com/PostHog/posthog-js/assets/12142999/d6486958-98ca-4d8e-a6d2-39cb597917c3">

**Comment by jakeonrails** [comment]
I got 350k of these in a day for a very low volume website using Rails 7 + Turbo and Posthog. Might have to discontinue Posthog unless there's a fix!

**Comment by glassworks-projects** [comment]
seeing this as well.

**Comment by earnold** [comment]
Are there any updates on this? I'm running into the same issue.

**Comment by pauldambra** [comment]
I don't have a rails site set up to test turbo but found this note in the docs

https://turbo.hotwired.dev/handbook/building#working-with-script-elements

> Annotate <script> elements with data-turbo-eval="false" if you do not want Turbo to evaluate them after rendering. Note that this annotation will not prevent your browser from evaluating scripts on the initial page load.

Are people with this problem using posthog via the snippet? If so can they try adding `data-turbo-eval="false"` to the script tag?

**Comment by earnold** [comment]
> I don't have a rails site set up to test turbo but found this note in the docs
> 
> https://turbo.hotwired.dev/handbook/building#working-with-script-elements
> 
> > Annotate <script> elements with data-turbo-eval="false" if you do not want Turbo to evaluate them after rendering. Note that this annotation will not prevent your browser from evaluating scripts on the initial page load.
> 
> Are people with this problem using posthog via the snippet? If so can they try adding `data-turbo-eval="false"` to the script tag?

@pauldambra - that could potentially work; however, there will be an issue when you explicitly want the script tag to be reevaluated. 

For example, when someone goes from a logged out to logged in state and you'd want to add a ` posthog.identify` call.

**Comment by pauldambra** [comment]
> when you explicitly want the script tag to be reevaluated.
> For example, when someone goes from a logged out to logged in state and you'd want to add a  posthog.identify call.

There is for sure some mismatch between turbo and posthog-js here.

Posthog-js should be evaluated once per page load. 

So, _I think_ we need to be able to opt-out of turbo's behaviour which is what I was hoping `data-turbo-eval="false"`. ofc if there's a better way to do it you all as users of turbo will likely figure it out better than us.

If you want to hold on to a reference to `posthog` so you can call `identify`, `reset`, `capture` etc that's fine (and the best way varies by application) but it shouldn't need you to evaluate the script tag more than once per page load

**Comment by stuartchaney** [comment]
Just installed today and currently getting slammed with these :/

Anyone ever find a workaround by any chance?

**Comment by pauldambra** [comment]
> So, I think we need to be able to opt-out of turbo's behaviour which is what I was hoping data-turbo-eval="false". ofc if there's a better way to do it you all as users of turbo will likely figure it out better than us.

> If you want to hold on to a reference to posthog so you can call identify, reset, capture etc that's fine (and the best way varies by application) but it shouldn't need you to evaluate the script tag more than once per page load

Hey @stuartchaney are you able to test this?

**Comment by earnold** [comment]
@stuartchaney The `data-turbo-eval="false"` has been working well for us.

**Comment by pauldambra** [comment]
I'll close this since we've found out how to have the turbo and posthog co-exist peacefully here https://github.com/PostHog/posthog-js/issues/666#issuecomment-2026323030

thanks for bearing with us all

**Comment by stuartchaney** [comment]
@earnold @pauldambra - awesome, thank you both - implementing now.

**Comment by oalexdoda** [comment]
How can we add `data-turbo-eval="false"` while using the Next.js / React SDK?

![Screenshot 2024-07-12 at 8 58 55 PM](https://github.com/user-attachments/assets/f6ec99a1-bd7d-4e06-885c-dccbfbd9fcc3)

**Comment by flamincode** [comment]
Hey, just added the snippet to our NextJS site, and are seeing this issue. `data-turbo-eval="false"` is has not resolved the error. Anyone have insight into other steps that have worked?
