### ISSUE TITLE
Issue with rrweb dep when compile for angular /ts app

### ISSUE THREAD

**Issue by jonssonjens** [PostHog/posthog-js#669]
![image](https://github.com/PostHog/posthog-js/assets/11965564/941d4496-7f96-4bda-b41d-cea2d05e206d)
We get the following error when trying to run our app using posthog-js.

Tried with installning rrweb and rrweb-snapshot but no difference..

**Comment by benjackwhite** [comment]
This should be fixed now. Sorry about this. We always had some weird typing issues as we are trying to keep the bundle as small as possible but this should be a "proper" fix now 👍
