### ISSUE TITLE
Disable tracking for users that are logged in to PostHog

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog-js#67]
// Continuing [the discussion](https://github.com/PostHog/posthog-js/pull/48#issuecomment-655479020) in #48 here.

I'd personally prefer to always remove "local" traffic, as a site admins almost always have different behaviour patterns than the real users. Thus they tend to skew the results and quite substantially on a low traffic site. For example, I was once investigating an interesting user's behaviour for kea.js.org, only to later discover it was me.

On all my other projects I always have lines like `<% if logged_out or not_admin %><%= google_javascript_snippet %><% endif %>` to hide all tracking for admins. Since posthog gives me a nice toolbar to play with, I'd definitely enable it, but would like an option to disable sending all events for myself. Probably the existing `posthog.init('KEY', { opt_out_capturing_by_default: true })` would do the trick, but I didn't test it. This is anyway an option only for dynamic websites with an authentication system... and not static ones like posthog.com or kea.js.org.

I found this behaviour with kea.js.org for three different cases:

1. Random unauthenticated site visitor: autocapture enabled and all pageviews are captured
2. User who has logged in to posthog (`/decide` returns `isAuthenticated=true`), but not authorized for the toolbar (`temporaryToken` is null): autocapture enabled and all pageviews are captured... like for random users.
3. Logged in and authorized the toolbar - this is where it gets weird: autocapture is disabled, yet $pageviews are captured. 

Debugging the third case further, I found the issue for those tracked $pageviews. I'm using the wonderful [posthog docusaurus integration](https://posthog.com/docs/integrations/docusaurus-integration), which manually calls `window.posthog.capture('$pageview')` every time the URL changes. 

I'd suggest for case 3 to disable sending of all events, so that we wouldn't have to add very specific "if using toolbar do nothing" code to all the integrations.

Personally I would also disable sending all events (autocapture and manual) for case 2. I would remove them from my site myself, but since it's a static page, there's no way to know that I'm visiting... other than from within the library after /decide.

For users we can say simply to test their page incognito... or we could make "Track users that are logged in to posthog" a configurable option under /setup.

**Comment by mariusandra** [comment]
I guess this is superseded by https://github.com/PostHog/posthog/issues/1352

**Comment by bryanltobing** [comment]
any update on how to do this?
