### ISSUE TITLE
Uncaught TypeError: posthog.group is not a function

### ISSUE THREAD

**Issue by loicknuchel** [PostHog/posthog-js#702]
Hi,

I'm setting up PostHog with groups but when I call `posthog.group` I got the `Uncaught TypeError: posthog.group is not a function` error :cry: 

I'm using PostHog could with the paid plan and enabled groups.
I use the Web snippet from https://eu.posthog.com/project/settings

My current PR: https://github.com/azimuttapp/azimutt/pull/236/files#diff-860c4340eaef04bb3df82eb7dbc0f15fb1bfa97cf90368b9b2305679fee7a3c0L5

Anything I missed?
Thanks!

**Comment by KrunchMuffin** [comment]
I am getting this as well. I just implemented it yesterday

**Comment by neilkakkar** [comment]
Looks like our issue, thanks for raising! The snippet doesn't expose this function. I'll update the snippet, but for now you can just add group to the list of functions in the snippet.

**Comment by loicknuchel** [comment]
It worked: https://github.com/azimuttapp/azimutt/pull/236/commits/c48ab174560041295921097cfe8156f7130c68e7
Thanks!
