### ISSUE TITLE
Option to disable $feature_view and $feature_interaction events

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog-js#707]
We are using the `PostHogFeature` component, however we're seeing unwanted `$feature_view` and `$feature_interaction` events in certain scenarios.

We use the same flag to control the navigation menu in our app, so are seeing `$feature_view` when the menu is on screen - this to us doesn't qualify a "view" of the actual feature.

Example on how this could be done?

```tsx
<PostHogFeature flag={feature} match={true} captureFeatureView={false} captureFeatureInteraction{false}>
    <h1>I'm on</h1>
</PostHogFeature>
```

**Comment by neilkakkar** [comment]
Hey @joesaunderson , just so I understand properly, you have two places controlled via the flag: the navigation menu & the actual page - and you want to use the component in both places, but only want enriched analytics in the actual page?

**Comment by neilkakkar** [comment]
Makes sense, good call, will add & publish tomorrow, thanks!
