### ISSUE TITLE
Toolbar not loading or displaying - TypeError: posthog.loadToolbar is not a function

### ISSUE THREAD

**Issue by lukyncze** [PostHog/posthog-js#718]
I have issue with displaying toolbar. I tried [this](https://posthog.com/docs/product-analytics/toolbar#troubleshooting-and-faq) without any success. Now I am getting this error: `TypeError: posthog.loadToolbar is not a function`.

I used JS snippet in index.html (Angular app): https://posthog.com/docs/getting-started/install?tab=snippet#add-to-your-website--app

My code:

```
posthog.init('MY_CREDENTIALS', { api_host: 'https://app.posthog.com' });

const toolbarJSON = new URLSearchParams(window.location.hash.substring(1)).get('__posthog')

if (toolbarJSON) {
    posthog.loadToolbar(JSON.parse(toolbarJSON))
}
```

**Comment by pauldambra** [comment]
sorry nobody replied here.. a lot of time has passed so i'll close this, feel free to reopen if needed!

**Comment by lukyncze** [comment]
Back then I realized that it is better to install posthog-js as a dependency. 😃 Thank you!

https://www.npmjs.com/package/posthog-js
