### ISSUE TITLE
Wrong feature flag values in cache and /decide endpoint response

### ISSUE THREAD

**Issue by algosdev** [PostHog/posthog-js#728]
### **Environment**:
`"posthog-js": "^1.68.5"`
`"react": "17.0.1",`

### **Current behavior**:
Having weird issue with feature flag values. 
Wrong feature flag values are fetched/cached, seems they are always ```false```.
- Posthog initialization:
```
 posthog.init(process.env.REACT_APP_PUBLIC_POSTHOG_KEY, {
      api_host: process.env.REACT_APP_PUBLIC_POSTHOG_HOST,
      // Not passing 'persistence' as its default value is 'cookie'
    });
```
- `/decide` endpoint response:
<img width="485" alt="image" src="https://github.com/PostHog/posthog-js/assets/68058088/1b09b7f6-7293-4a0c-a5c0-717a5a49a696">

- actual values of feature flags in Posthog admin panel:
<img width="743" alt="image" src="https://github.com/PostHog/posthog-js/assets/68058088/ac0f3186-f691-4552-83fd-7644180209fa">

### **Expected behavior:**
Correct feature values should be fetched/cached (like shown in admin panel - `true` for all).

Once I set `persistence: 'memory'` and reload, correct feature flag values are fetched.

**Comment by neilkakkar** [comment]
Mind pasting the decide request payload as well? And tell me your project ID?

I expect what's happening is that your flag has a property condition, and the decide request is sending different properties.

**Comment by algosdev** [comment]
Hey @neilkakkar  I thought the issue is only when using cache, but can be reproduced even with `persistence: 'memory'` option. We released PostHog implementation in our project today and reverted back after sometime due to this issue.

Not sure if it's ok to share projectId and payload publicly here, so pasting some screenshots with blurred sensitive data.

Request payload (token parsed in jwt.io):

<img width="1108" alt="image" src="https://github.com/PostHog/posthog-js/assets/68058088/84009f03-1892-405d-9fca-abd8d7df3040">



Response payload to the exact request:

<img width="852" alt="image" src="https://github.com/PostHog/posthog-js/assets/68058088/f9a31ab5-1ca6-4bc4-a00f-87c12bb80240">



The condition of feature flag (the same for both):

<img width="664" alt="image" src="https://github.com/PostHog/posthog-js/assets/68058088/bb2f5021-fd96-40d9-979f-5d087d0fa6d5">



Actual feature flag values in admin panel:

<img width="1165" alt="image" src="https://github.com/PostHog/posthog-js/assets/68058088/6e734592-97a9-4eda-a95e-1bc597f9956f">

Hoping I shared enough data. What I know is there is inconsistency, for some users it's working well. Would appreciate if you can help us!

**Comment by neilkakkar** [comment]
I bet what's happening here is that when you call `posthog.identify()` the account_id is a number, but on the flag it's a string. If you update your person property in `posthog.identify()` to be a string, this should work.

When it goes to the database, it does a case insensitive match. We'll soon be bringing this case-insensitive matching to property overrides too, which should ensure this problem doesn't show up in the future.

Let me know / reopen if this doesn't solve it for now!

**Comment by algosdev** [comment]
I got it! Do you have any explanation to inconsistency: why it worked for some users? Is there anything specific to first load of posthog - calling identify() for the first time and onFeatureFlags()

**Comment by neilkakkar** [comment]
Were the users with account id 2 or 23722?

If yes:

1. When you identify(), you're setting the accountID person property override
2. However, if persistence is memory, this is lost on refresh
3. if identify is not called again on refresh, say, since you're already logged in, then this property is not sent with decide
4. In this case, it uses the property stored in our database instead of the override, which is type insensitive matching
5. Hence, it works fine.

**Comment by algosdev** [comment]
Thanks a lot @neilkakkar

**Comment by algosdev** [comment]
Hey @neilkakkar! We thought after number -> string conversion, the issue is fixed, (reduced much) but seeing inconsistency (only for some users, mostly on the first load).

For this user feature flag value was fired as `false`, where it should be `true`. Because he is part of At Members [PROD] cohort (condition of `mentions` feature flag).


<img width="300" alt="image" src="https://github.com/PostHog/posthog-js/assets/68058088/a259772b-de80-4d8c-8fda-3a726896b947">
<img width="300" alt="image" src="https://github.com/PostHog/posthog-js/assets/68058088/e7c738a6-fc21-445e-a02f-052962a46d40">
<img width="300" alt="image" src="https://github.com/PostHog/posthog-js/assets/68058088/6d949ae0-d9e9-4258-94b7-75aad162e651">


I ensure that user properties are string. Also pasting latest/whole implementation code:

```
const withPostHogProvider = Component => props => {
  const user = useAuthUser();
  const posthogClient = useMemo(
    () =>
      posthog.init(process.env.REACT_APP_PUBLIC_POSTHOG_KEY, {
        api_host: process.env.REACT_APP_PUBLIC_POSTHOG_HOST,
        bootstrap: {
          distinctID: String(user.memberId) // to prevent random anonymous id generation
        },
      }),
    []
  );

  useEffect(() => {
    if (user.memberId && posthogClient) {
      const memberId = String(user.memberId);
      const normalizedProperties = {
        user_member_id: memberId,
        user_fullname: user.fullname,
        account_id: String(user.company.id)
      };
      posthogClient.setPersonPropertiesForFlags(normalizedProperties);
      posthogClient.identify(memberId, normalizedProperties);
    }
  }, [user.memberId, posthogClient]);

  return (
    <PostHogProvider client={posthog}>
      <Component {...props} />
    </PostHogProvider>
  );
};
```

Hoping I provided enough data. Can you spot anything weird, still not sure if it is a bug from PostHog or our implementation.

**Comment by neilkakkar** [comment]
Yep, in this case, the problem is the bootstrap: You're changing the distinct ID, but not providing any flags, so all flags are false, until the flag reload happens. To prevent this, when you bootstrap, you should add flag values as well, or alternatively disable loading flags on first load (when user can be anonymous) - this feature is coming today!: https://github.com/PostHog/posthog.com/pull/6330

**Comment by algosdev** [comment]
Excited about new feature!

As far as I know we're calling init() and identify() and there are two /decide requests. I'm aware that in the first request, feature flag value is false(because we are not sending user properties in it). We do not want to bootstrap, but rely on second request which is triggered by identify().

Are you saying that `Feature Flag Called` event in admin panel is for the first request which is without user properties?
I thought it's for identified user since it's being logged after `Identify` event and there is only one `Feature Flag Called` even though there are two /decide requests:

<img width="964" alt="image" src="https://github.com/PostHog/posthog-js/assets/68058088/7f42e4ce-1d36-4ee7-8d1f-312a58cca7e2">

**Comment by neilkakkar** [comment]
It's hard to tell, it depends on when the flag call happens: if it happens between init and identify, then it's for the first one. If it's after, it's for the second one. Even if the event happens after `identify`, it could be that it happens before the `/decide` request returns after identify, in which case it will still be using the old values.

Possibly easier to check if you debug the decide calls as they happen.

Also worth noting here that `Feature Flag Called` events are not an audit for every call: If you call `getFeatureFlag()` 3 times, and the response doesn't change, we'll only send one event (as otherwise your number of events can really blow up)
