### ISSUE TITLE
Page View and Page leave events are still sent when capture_pageview and capture_pageleave are set to false in init in Javascript SDK

### ISSUE THREAD

**Issue by anthony-sherloq** [PostHog/posthog-js#735]
Env:
1. React
2. Posthog JS sdk version: 1.68.2
3. node version 16.20.0

Steps to reproduce: 
1. call init with config: 
    ` {
                api_host: API_HOST,
                debug: APP_ENV === 'development',
                capture_pageview: false,
                capture_pageleave: false,
                autocapture: false,
            },
`
4. Monitor events in posthog console

**Comment by navinpai** [comment]
@anthony-sherloq @macobo Do we have any fixes for this issue? We're seeing the same issue as well with the same config shown above: `capture_pageview: false, capture_pageleave: false, autocapture: false`

**Comment by SlawomirMazgaj** [comment]
Experiencing the same thing.

`"posthog-js": "^1.116.2"`

**Comment by pauldambra** [comment]
I added a test to confirm and we've fixed this since it was reported
sorry nobody replied here

**Comment by chetanatennoventure** [comment]
Hi, we're currently facing the issue where pageleave events are automatically captured though capture_pageleave & capture_pageview is set to false. It's happening only for pageleave event. I have updated to latest version - 1.184.2, still the issue exists. Please can you let me know what information is needed so this issue can be checked.
