### ISSUE TITLE
`isFeatureEnabled` with bootstrapped flags

### ISSUE THREAD

**Issue by joshkel** [PostHog/posthog-js#737]
We bootstrap PostHog with feature flags initialized to default:

```ts
  postHog.init(token, {
    bootstrap: {
      featureFlags: {
        featureA: false,
        featureB: false
      }
    },
  });
```

Then we use `onFeatureFlags` to respond to changes to those flags:

```ts
  postHog.onFeatureFlags(() => {
    updateFeatureA(postHog.isFeatureEnabled('featureA'));
    updateFeatureB(postHog.isFeatureEnabled('featureB'));
  });
```

However, we've noticed spurious warnings in the browser console that feature flags didn't load in time:

```
153.7b313cca.js:2 isFeatureEnabled for key "featureA" failed. Feature flags didn't load in time.
153.7b313cca.js:2 isFeatureEnabled for key "featureB" failed. Feature flags didn't load in time.
```

And `isFeatureEnabled` returns undefined, rather than reporting that bootstrapped flags are set to false, as expected.

If I understand correctly, the following sequence of events is occurring:

* Any falsy bootstrapped flags are ignored. (See [here](https://github.com/PostHog/posthog-js/blob/ca899de7360f42a0faaeb6def75e0a61b03dc3fa/src/posthog-core.ts#L464).)
* Because flags have been bootstrapped, the `onFeatureFlags` callback is immediately invoked. (This isn't what I expected, but I can understand it.)
* Because no feature flags are actually enabled, calling `isFeatureEnabled` throws a warning. (This may be a mistake - not having any flags enabled is a legitimate condition. It appears to be the result of [this change](https://github.com/PostHog/posthog-js/commit/d583d644e05a882762a9f7130edccd3102a35b30#diff-8af751c29c92de49f1220a34f3293d52755a0faacb360d38838065084a97c8ebR211).)

**Comment by neilkakkar** [comment]
Thanks @joshkel , makes sense, will fix this
