### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'throttleMutations')

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog-js#764]
```
sessionrecording.ts:327 Uncaught TypeError: Cannot read properties of undefined (reading 'throttleMutations')
    at e.value (sessionrecording.ts:327:17)
    at e.value (web-performance.ts:209:17)
    at e.value (web-performance.ts:183:14)
    at web-performance.ts:104:21
    at Array.forEach (<anonymous>)
    at PerformanceObserver.<anonymous> (web-performance.ts:104:42)
```

Config:

```
capture_pageview: false,
capture_pageleave: false,
disable_session_recording: true,
autocapture: false,
```

This happens _a lot_...

**Comment by benjackwhite** [comment]
Is this still happening? We detected this pretty immediately and [pushed out a fix](https://github.com/PostHog/posthog-js/pull/763).

What version are you using?

**Comment by joesaunderson** [comment]
What’s the best way to tell? This is on a legacy page which doesn’t use the library, instead using the standard script tag. 

I suppose that could be cached? Is there a way to see what version of the script tag is running?

**Comment by benjackwhite** [comment]
If its being loaded by the script tag then it should be the latest version. It could indeed be cached by the browser though. You can probably see in PostHog itself by looking at the `$lib_version` property of events.

**Comment by joesaunderson** [comment]
Seems to happen even when disabling the cache, and difficult to find version as we're purposely not sending any events / disabling session recording here.

Looking in my sources panel, it does seem to be on the new version though:

![image](https://github.com/PostHog/posthog-js/assets/11272509/f1c27ba5-e50c-4e16-9fbe-44de08a58550)

**Comment by benjackwhite** [comment]
Is there somewhere you can link me so I can take a look myself?

**Comment by joesaunderson** [comment]
For the curious, myself and Ben are now chatting on Slack (I gave access to our authenticated portal).

**Comment by joesaunderson** [comment]
Cause of this was... caching! (On our reverse proxy)
