### ISSUE TITLE
Different variants and distinct IDs in experiment 

### ISSUE THREAD

**Issue by spiceee** [PostHog/posthog-js#781]
Hi,

I'm new to PostHog, and we're running our first experiment. We assign a distinct ID in ` posthog.init`, and I see I get assigned to different variants (between control and test) with the same ID if I reload the page with the experiment on.

Is this the expected behavior? Or should a distinct ID be locked to a variant for a given experiment?

I couldn't find any clarification on the docs for this issue.

Thanks.

**Comment by neilkakkar** [comment]
Hey @spiceee , this shouldn't happen given the same ID -it should lock the variant, could you please write down a minimal reproducible example here so I can help debug?

Thanks!

**Comment by spiceee** [comment]
@neilkakkar Turns out we were using a tracking id that did update on every refresh so the problem was on our end. Thanks!
