### ISSUE TITLE
get_distinct_id in Nextjs Client Component Throws Err

### ISSUE THREAD

**Issue by SamKomesarook** [PostHog/posthog-js#782]
When importing `get_distinct_id` to call in a NextJS13 client component, we receive the following err:

`TypeError: this.persistence is undefined`

We are attempting to call it in an href string to append the user id as a route param.

**Comment by pauldambra** [comment]
we've improved type safety and clarity around what is or isn't undefined a lot since this was logged
i'll close it, but feel free to reopen if still happening for you
