### ISSUE TITLE
"Cannot find module 'posthog-surveys-types'" with posthog-js 1.77.3 and later

### ISSUE THREAD

**Issue by roschlau** [PostHog/posthog-js#807]
We're getting this error when trying to build our app with any posthog-js version >= 1.77.3, including up to 1.81.0:

```
Error: node_modules/posthog-js/dist/module.d.ts:1:32 - error TS2307: Cannot find module 'posthog-surveys-types' or its corresponding type declarations.
1 import { SurveyCallback } from 'posthog-surveys-types';
                                 ~~~~~~~~~~~~~~~~~~~~~~~
```

We've temporarily pinned our version to 1.77.2 to keep our build working, but a fix for this or any info on what to fix on our end would be appreciated.

**Comment by kunal-singh** [comment]
+1

**Comment by neilkakkar** [comment]
Thanks for the report! Let me put a quick fix in for this 👀  -> same as https://github.com/PostHog/posthog-js/issues/698 - there's something really wrong here with the module generation 🤔

**Comment by tb-b** [comment]
I'm still running into this on 1.82.2
`Cannot find module 'posthog-surveys-types' or its corresponding type declarations.
import { SurveyCallback as SurveyCallback$1 } from 'posthog-surveys-types';`

**Comment by neilkakkar** [comment]
Thanks @tb-b , looks like this broke again in 1.82.0. Need to find a more permanent fix - will update this, thanks!
