### ISSUE TITLE
Feature Request: Optional trailing slash

### ISSUE THREAD

**Issue by yvesbuschor** [PostHog/posthog-js#814]
### Situation
The Posthog API works with trailing slashes (e.g. `/decide/?v=3` and not `/decide?v=3`). This is hardcoded in the posthog-js library which generally makes sense.

### Problem
For people working with a reverse proxy (e.g. [with Vercel](https://posthog.com/docs/advanced/proxy/vercel)) the endpoint that gets called still has that trailing slash. Next.js and Vercel by default redirect to the endpoint without trailing slash (this could be overwritten but only for the whole site -  see [Next.js docs](https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash)).
This causes every request to the reverse proxy to first trigger a redirect with 308.
![posthog-redirect](https://github.com/PostHog/posthog-js/assets/5999628/4c664a38-d4d1-4233-9c53-28e4692ff3ca)

While the 308 can't be avoided without changing the global trailing slash config, the reverse proxy can still redirected correctly by re-adding the slash.
For example a working reverse proxy for Next.js with default config:
```
    "rewrites": [
      {
        "source": "/ingest/:match*",
        "destination": "https://eu.posthog.com/:match*/"
      }
    ]
```

### Proposed Feature
In the posthog.init function add a config option `trailing_slash` (type: Boolean, default: true).
If set to false, requests wouldn't include the trailing slash. Thus not triggering a 308 in the situation described above.

### Open Questions
I think not all endpoints work without trailing slash. (e.g. we had issues when loading the site-app for survey beta). This means disabling trailing slash should only be possible when there's a reverse proxy set up like above adding the trailing slash back again.

So I'm not sure if this is something that should actually be part of the library or just a documented limitation. Without the change people using Next.js without trailing slashes won't be able to use the rewrite function for reverse proxy or have to accept the redirect loops.

(Happy to create a PR but would first like to hear some opinions)

**Comment by fabianuribe** [comment]
I am also observing the redirects happening for all Posthog requests when using the reverse proxy approach with Next.JS, due to [Next.JS default handling of trailing slashes](https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash). 

I think @yvesbuschor proposal to expose a config would be definitely be welcomed, since it would halve the number of requests to the proxy. Although to be fair, it is a Next.JS specific issue and I am not sure whether Posthog _should_ be concerned or would event want work around other framework's limitations. For what is worth, my solution was to strip the trailing slash at the edge using [Cloudflare's URL rewrite rules ](https://developers.cloudflare.com/rules/transform/url-rewrite/). So far,  I don't observe any meaningful latency increase due to the rewrites and it effectively takes care of all those unnecessary redirects and effectively reduced ~30% of our posthog's aggregate request times.

### Without rewrites
<img width="1189" alt="Screenshot 2023-12-09 at 5 46 47 PM" src="https://github.com/PostHog/posthog-js/assets/2894201/4352b14b-d109-4ac4-8dfa-f347838756a2">

### With rewrites
<img width="1189" alt="Screenshot 2023-12-09 at 5 49 27 PM" src="https://github.com/PostHog/posthog-js/assets/2894201/123e789e-f933-4180-99ca-569df259c726">

**Comment by viantirreau** [comment]
Hi @fabianuribe!

Could you share more details about your solution using Cloudflare URL Rewrite rules?
I think I could manage to do it with the `regex_replace` function, but apparently, I need a Business plan or a WAF Advanced plan to be able to use that function.

Thanks in advance!

**Comment by fabianuribe** [comment]
> Hi @fabianuribe!
> 
> Could you share more details about your solution using Cloudflare URL Rewrite rules? I think I could manage to do it with the `regex_replace` function, but apparently, I need a Business plan or a WAF Advanced plan to be able to use that function.
> 
> Thanks in advance!

Hey @viantirreau , I believe you get 10 rewrite rules even on Free Plan.

Here is what my rule configs look like, I hope it helps:

Under: `Rules` > `Transform Rules` > `Rewrite Rules` 

<img width="920" alt="Screenshot 2024-01-10 at 11 52 31 PM" src="https://github.com/PostHog/posthog-js/assets/2894201/20120a7a-a114-4b85-9848-6b102aa55489">

<img width="926" alt="Screenshot 2024-01-10 at 11 52 59 PM" src="https://github.com/PostHog/posthog-js/assets/2894201/eb13852d-1b10-4a4c-b0a6-8addebcd3155">

**Comment by viantirreau** [comment]
Brilliant!
Works like a charm. Thank you!

**Comment by robmarshall** [comment]
Some additional context. It is not possible to use this in Capacitor JS as a 308 redirect is seen as a CORs issue. The app is already in existence without trailing slashes. We would need to change all the endpoints for this to work.

**Comment by mustafa421** [comment]
Following. Is there any other workaround for those not using Cloudflare or Vercel?

**Comment by florianjuengermann** [comment]
With nextjs you can now disable the trailingbackslash redirect:
```
// next.config.js
module.exports = {
  skipTrailingSlashRedirect: true,
}
```

https://nextjs.org/docs/app/building-your-application/routing/middleware#advanced-middleware-flags

**Comment by florianjuengermann** [comment]
@robmarshall Yes I have a setup with nextjs & vercel that works now. What is your issue?

My config:
```javascript
// next.config.js
module.exports = {

 skipTrailingSlashRedirect: true,
  async rewrites() {
    return [
      {
        source: "/ingest/:path(.*)",
        destination: "https://us.i.posthog.com/:path",
      },
      {
        source: "/ingest/static/:path(.*)",
        destination: "https://us-assets.i.posthog.com/static/:path",
      },
    ];
  },
}
```


```typescript
// posthog_provider.ts
posthog.init(process.env.NEXT_PUBLIC_POSTHOG_KEY!, {
  api_host: "/ingest",
  ui_host: "https://app.posthog.com",
});
```

**Comment by zlwaterfield** [comment]
> With nextjs you can now disable the trailingbackslash redirect:
> 
> ```
> // next.config.js
> module.exports = {
>   skipTrailingSlashRedirect: true,
> }
> ```
> 
> [nextjs.org/docs/app/building-your-application/routing/middleware#advanced-middleware-flags](https://nextjs.org/docs/app/building-your-application/routing/middleware#advanced-middleware-flags)

Incredible find, thank you @florianjuengermann! I just tested for rewrites, API routes and middleware, and it works for all three. 

I am going to update the docs today with this.

**Comment by zlwaterfield** [comment]
I'm going to close this issue because this looks to have a solution now.
