### ISSUE TITLE
Cohorts missing filter options

### ISSUE THREAD

**Issue by spodaras** [PostHog/posthog-js#817]
Hello, I am trying to set up cohorts to track first-time and returning user, as described here:
[Track new returning users](https://posthog.com/tutorials/track-new-returning-users)

Unfortunately, I don't have the option "Completed an event for the first time" available in the dropdown:
![grafik](https://github.com/PostHog/posthog-js/assets/115463174/311efb35-69d3-4dd1-b890-35742d25b4bf)

Also, all filter options described here are also missing:
[Array 1.37.0](https://posthog.com/blog/the-posthog-array-1-37-0)

Can anyone explain to my why I don't see this options? Is this a bug? To mee it seems they should be available in the free plan....

**Comment by neilkakkar** [comment]
Hey @spodaras this looks like an unfortunate UI bug, you should be able to scroll in the list to see all those options below the current options you see.

(P.s: The right repo for this issue is Posthog/posthog: https://github.com/PostHog/posthog

**Comment by spodaras** [comment]
@neilkakkar Hello, unfortunately, I cannot scroll or navigate with the arrow-keys or tab either :-( 
Neither on Firefox nor on Chrome.
Shall I open the issue in the other repo?

**Comment by neilkakkar** [comment]
oh, hmm, are you self hosting perhaps? Or is this in app.posthog.com? If the former, you might need to upgrade to latest

**Comment by spodaras** [comment]
I am in the cloud, on app.posthog.com... ^_^

**Comment by neilkakkar** [comment]
oooh that doesn't make sense, let me have a look 👀  - what's your project called?

**Comment by spodaras** [comment]
Thanks, will send you a PM :)

**Comment by neilkakkar** [comment]
All sorted: This required a subscription to product-analytics, which wasn't really clear in the UI
