### ISSUE TITLE
posthog snippet breaks the website

### ISSUE THREAD

**Issue by vmachacek** [PostHog/posthog-js#818]
I made loading of the posthog script optional and when its present it breaks the javascript execution of the website, please check here

www.gilitickets.online and www.gilitickets.online/?addPosthog=true

please try in chrome and you can see in later case the form at the top of the page does not work

use google chrome to observe the behavior

**Comment by pauldambra** [comment]
also reported here https://posthog.com/questions/site-crashes-when-snippet-is-present-and-served-by-cloud-flare

**Comment by pauldambra** [comment]
The site works (there is a dropdown when clicking on "from") in Safari and Firefox

Have you tried without rocket loader?

**Comment by vmachacek** [comment]
@pauldambra when i turn off the rocket loader the site works fine.. I created ticket with CloudFlare but no response so far
