### ISSUE TITLE
Make localStorage+cookie the default persistence

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog-js#876]
We currently default to `cookie` for persistence which has the major issue that there are tight limits on how much can be stored.

More and more we rely on storage for relevant parameters such as registered properties or utm campaigns and `localStorage+cookie` works great for balancing the two.

To make this happen we need to:
1. Change the default
2. Change the startup logic to check cookie storage and migrate it to localstorage if there is no existing data in localstorage
3. That way it should mean that we can change the default without breaking anyones implementation.
4. We would still respect explicitly set persistence options.

**Comment by robbie-c** [comment]
Related thread https://posthog.slack.com/archives/C02E3BKC78F/p1698320675626999

**Comment by timgl** [comment]
Suggestion: keep the most important properties with sensible value limits in cookies so that they are still accurate cross-domain, but move everything else in localstorage. We should write up the list of properties we'll support cross domain.

**Comment by robbie-c** [comment]
Currently store [DISTINCT_ID, SESSION_ID, SESSION_RECORDING_IS_SAMPLED]
