### ISSUE TITLE
Reduce surveys size in persistence

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog-js#884]
We store surveys in persistence and there's a lot going on there which might be blowing up some cookies 🤔

**Comment by neilkakkar** [comment]
this will fix it: https://github.com/PostHog/posthog-js/issues/876

**Comment by liyiy** [comment]
I do feel bad about the large amount of surveys content so in addition to that permanent solution, it might still be worth downsizing a little when storing into persistence? 😅 idk

**Comment by neilkakkar** [comment]
not sure what you mean? We need the survey response to generate surveys to show. You could always send it to localstorage and never the cookie irrespective of global persistence setting if that helps.
