### ISSUE TITLE
We send "Mac OS X" for `$os` but the OS name is now `macOS`

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog-js#915]
It's an easy change to switch detection but we don't have a good story for "re-valuing" a built-in property like this.

A user has to know to query both values if they care about data before and after we made the change.

So we should:

1. make the change and announce it in the changelog
2. email users that have an insight using `Mac OS X` to tell them of the change and how to add another match value to their insight
3. update the UI taxonomy to mention the older value when you look at the description for `$os`

**Comment by marandaneto** [comment]
An alternative to making it back compatible is to just add a special case in the query generator, eg when `Mac OS X` is queried for, you add `macOS` as an `OR` operation, and vice versa.

**Comment by thmsobrmlr** [comment]
@mariusandra Would something like this warrant a HogQL modifier? I'm worrying a bit we're making our future lives harder by adding a lot of special cases.

**Comment by mariusandra** [comment]
I don't see the urgency here... and opt for option D --> doing nothing :).

As currently envisioned, there's no plan to override or merge properties. To keep things clean, HogQL's custom properties/columns/fields/lambdas would likely add something like `events.custom.priority_user = (event) -> (event.person.properties.email =~ '.*@openai.com')`.

However... we could think of a pure HogQL `properties` translation/cleanup/schema layer, and expose the old properties as `raw_properties`... 🤔. Not presently planned though 😅

**Comment by pauldambra** [comment]
No urgency! Storing the thought in an issue so I can not ignore it but also do nothing now.

Multiple votes for do nothing now is the winner 🥇

**Comment by pauldambra** [comment]
we'll not fix this at least until we've a way to rename old props
