### ISSUE TITLE
$pageleave events are sent when capture_pageview: false

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog-js#92]
## Bug description

I ran posthog-js with `{ autocapture: false, capture_pageview: false }` to avoid any automatic event capturing, however pageviews were still captured (below screenshot of request with pageview payload).

![image](https://user-images.githubusercontent.com/5864173/96001400-45fb8100-0e38-11eb-9f0a-637880c8090c.png)

## Expected behavior
- Page view events should not be sent on `capture_pageview: false`

## How to reproduce

1. Init posthog-js with `{ capture_pageview: false }` and review the JS requests console.

**Comment by macobo** [comment]
From testing, it seems to be related to $pageleave events instead.

**Comment by macobo** [comment]
Fix has been :ship: with version 1.6.0

**Comment by joepavitt** [comment]
Seeing this same issue now with the `$pageleave` event registering, despite having `capture_pageview: false` in the config. The comment above says fixed 18 months ago in `1.6.0`, I'm currently running `1.28.0`, but it still seems a problem?

**Comment by anthony-sherloq** [comment]
@macobo I have reproduced this bug in issue. Can you take a look?
#735
