### ISSUE TITLE
Add support for gbraid, wbraid, fbclid, igclid url params

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog-js#922]
Google is making some changes to the way they handle tracking ids https://support.google.com/analytics/answer/11367152?hl=en so we should add these params. 

Also requested were some facebook ids (fbclid and igclid). 

Request: https://posthog.slack.com/archives/C03P7NL6RMW/p1701873581878649

I wonder if a generic mechanism to pass in a set of url properties to always capture would be useful?

**Comment by pauldambra** [comment]
@camerondeleone is this closeable?

**Comment by robbie-c** [comment]
Looks we don't do `igclid` but do `igshid`, @camerondeleone is this what you meant? When I search `igclid` then this issue is the top google search result 😎
