### ISSUE TITLE
Option to disable surveys in posthog-js config (like the `disableSessionRecording` config

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog-js#932]
I was looking at the year in posthog page to see if I'd made any silly performance mistakes

Session Recording is 28% of the JS the page loads
And surveys is 11%

I know that I don't want to put a survey on the page. But I couldn't see how to disable surveys only for that page

I expected `disableSuryeys` config option. So that I can have surveys on for the account, but off for this particular site that reports to it

**Comment by liyiy** [comment]
This is a good point especially as the surveys JS is probably only going to get bigger. What did you mean by configuring it off for this particular site that reports to it though? I don't quite understand why someone would set that config option for a page even if it's a page they don't want surveys on, like why would a user want to do that and what do they gain by doing it? 😮

**Comment by liyiy** [comment]
Ok so it would primarily be a performance aspect?

**Comment by pauldambra** [comment]
Yep 👍
