### ISSUE TITLE
Convert surveys js code into components

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog-js#947]
## Request
Surveys is currently written in pure JS right now which makes the UI code for it difficult to parse.

We want to componentize it so that it's easier to develop on (and possibly create a re-useable library of surveys components eventually) while trying to keep it as lightweight as possible.

## Questions:

1. Are there any reasons this would not be worth doing?
2. Where does this live? Inside of posthog-js still, in its own library? Like /src vs /react
3. Suggestions on libraries if not react? (Ben recommends preact here)
4. Besides making sure that surveys works and that the final output size is not too big, Is there anything else I should look out for while moving this over?

**Comment by benjackwhite** [comment]
My 2 cents here (I've built this sort of thing before so somewhat well versed...)

> 1. Are there any reasons this would not be worth doing?

Nope! The purists will say that the extra bundle size is not worth it - just use vanilla JS! In reality we can offer a better and more flexible product faster if we use some sort of framework. It's definitely not _optimal_ but thats something we can solve for later. We should still choose wisely _which_ framework though with an optimization for low foot print (bundle size, memory etc.)

> 2. Where does this live? Inside of posthog-js still, in its own library? Like /src vs /react

It may make sense to pull it out to its own sub-folder and "package-ize" the repo so its easier to manage.
The most important thing is that we don't accidentally import the surveys stuff into the main JS. Currently a rogue import could lead to that, whereas properly separating it out would avoid it.

> 3. Suggestions on libraries if not react? (Ben recommends preact here)

React is great but beefy. Feels like the right choice given the common skills and experience we have here.
Preact is way more limited but largely provides the benefit of being much smaller (important for keeping in the good books of our user's users) and so close to React's API that if we would swap to it in the future it shouldn't be too painful.

> 4. Besides making sure that surveys works and that the final output size is not too big, Is there anything else I should look out for while moving this over?

We shouldn't over-optimize for this yet but we should definitely consider the choice of styling library we are using to ensure we don't back ourselves into a corner when it comes to future styling 


@Twixes you're always pretty up-to-date in this world. Thoughts?

My suggestion would be to try this out - Get a minimal setup working in its own folder like the `/react` folder. That way we can bundle the code and see what the base size is between react / preact and any other deps we might need. Should be clear what the path forward should be at that point

**Comment by Twixes** [comment]
I'm not a fan of having our users' users load a whole copy of React, but Preact does sound really good. [Svelte](https://svelte.dev/) is a different compact option that could be interesting, but it definitely has a learning curve coming from React, while Preact pretty much doesn't.

Exported survey components would be cool too, and that probably means React. Though if there's not explicit demand for it, I would rather prioritize bundle size. Either way with Preact the migration path should be simple if we ever need it.

**Comment by mariusandra** [comment]
+1 for Preact. It has some rough edges if you use a weird set of old libraries, but generally works really well. I was considering trying it at one point to making our regular `<iframe />` embeds quicker, but didn't get to as we'd need to load most of antd anyway.

Another react-compatible (and faster) library is https://www.infernojs.org/ . The original dev went to work for React at one point, and now works for Svelte. The project itself still seems rather active under its new management though.

**Comment by liyiy** [comment]
preact it is! thank you for the suggestions 😃
