### ISSUE TITLE
When I use posthog.get_distinct_id() posthog.get_distinct_id is not a function

### ISSUE THREAD

**Issue by npm-ued** [PostHog/posthog-js#960]
as the title when i use get_distinct_id() method, posthog.get_distinct_id is not a function.
how can i use get_distinct_id method in frontend 

`
    !function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.async=!0,p.src=s.api_host+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="capture identify alias people.set people.set_once set_config register register_once unregister opt_out_capturing has_opted_out_capturing opt_in_capturing reset isFeatureEnabled onFeatureFlags getFeatureFlag getFeatureFlagPayload reloadFeatureFlags group updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures getActiveMatchingSurveys getSurveys".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);

    posthog.init('xxx',{api_host:'https://xx.xx.com'})
    posthog.register({
      project: "test"
    });

    // console.log(posthog);

    // console.log(posthog.get_distinct_id());
`js

**Comment by neilkakkar** [comment]
Hi @npm-ued , it seems like the snippet you're using doesn't have this function, you can update the snippet to get this, like so:

```
getActiveMatchingSurveys getSurveys get_distinct_id
```

(i.e add the function at the end of existing functions in the snippet)

**Comment by npm-ued** [comment]
But I still have a question. When I clear the browser cookie and localstorage and get distinct_id again, how can I distinct_id still be the same? By default, it is stored in a cookie. Is the distinct_id set by the server?
