### ISSUE TITLE
`console.dir` produces `rrweb logger error:`

### ISSUE THREAD

**Issue by bitjson** [PostHog/posthog-js#967]
[My application](https://github.com/bitauth/bitauth-ide) uses `console.dir` to log very large/complex objects to the console for advanced users to explore. `console.dir` provides a better UX across most browsers than `console.log` (even though, in most modern browsers, `console.log` doesn't always attempt to convert values to a string).

Is there some workaround to tell PostHog to pretend `console.dir` is `console.log`, or even to disable rrweb on `console.dir` calls?

Thanks!

**Comment by bitjson** [comment]
Ah, no error message was produced, so I assumed that `console.dir` wasn't expected to work.

It seems like most of the problem is #968, there's just a small additional issue here of `console.dir` not returning (some?) internal errors. When I pass a BigInt to `console.dir`, I see only `rrweb logger error:` and no further message or context.

**Comment by pauldambra** [comment]
I'll close this for now, and we can revisit it if #968 doesn't clear everything
