### ISSUE TITLE
module.d.ts: options is optional in opt_out_capturing(options)

### ISSUE THREAD

**Issue by stonesthatwhisper** [PostHog/posthog-js#97]
https://github.com/PostHog/posthog-js/blob/b2618295d3ae679f91fbfab3eff514141fd90d5d/src/module.d.ts#L397

It should probably be

    -static opt_out_capturing(options: posthog.OptInOutCapturingOptions): void
    +static opt_out_capturing(options?: posthog.OptInOutCapturingOptions): void

for options to be optional. Otherwise, typescript does not compile. Same thing for many other methods.

**Comment by macobo** [comment]
Thanks! I've fixed the error in https://github.com/PostHog/posthog-js/pull/98, will let you know once a new release is out.

Also feel free to open a PR directly in the future. :)

**Comment by mariusandra** [comment]
@macobo merged! Feel free to push out a new release when you verify the $session_id code works as advertised!

**Comment by macobo** [comment]
@stonesthatwhisper check out the new release and let us know if you run into any other issues
