### ISSUE TITLE
bundle size is inflated by use of TS/JS classes

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog-js#975]
terser and rollup don't minify class fields and methods so our bundle includes things like `this.sessionManager.checkAndGetSessionAndWindowId(!t,e.timestamp)` when you might expect it to include `o(!t,e.timestamp)` after minifying

session recording uses 2 classes: `session id manager` and `session recording` and uses long descriptive method names - and is ~ 13% of the final bundle

there is probably an easy win in moving some or all of this to function-based instead of class-based code

**Comment by fromaline** [comment]
Looks like the code uses a lot of classes

**Comment by fromaline** [comment]
@pauldambra, do you mean something like [this PR](https://github.com/PostHog/posthog-js/pull/978)?
