### ISSUE TITLE
Struggling with using PostHog and Security Headers

### ISSUE THREAD

**Issue by MathiasWP** [PostHog/posthog-js#976]
We're setting our Security Headers with Helmet.js' default values. PostHog is crashing because setting `Cross-Origin-Embedder-Policy` to `require-corp` requires the `crossorigin` attribute to be set to `anonymous`. How can this attribute be set on the PostHog scripts that are added during runtime?

Current workaround: Setting `Cross-Origin-Embedder-Policy` to `credentialless`, which is not ideal.

Screenshot of the error in Chrome:
<img width="1062" alt="Screenshot 2024-01-29 at 00 28 30" src="https://github.com/PostHog/posthog-js/assets/48158184/b43cc6d9-8719-439b-87bb-919a00c44df1">

**Comment by pauldambra** [comment]
Hey @MathiasWP 

I've not used COEP before and just reading up here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy#avoiding_coep_blockage_with_cors

> If you enable COEP using require-corp and have a cross origin resource that needs to be loaded, it needs to support CORS and you need to explicitly mark the resource as loadable from another origin to avoid blockage from COEP. 

> `<img src="https://thirdparty.com/img.png" crossorigin />`

----

eu.posthog.com should be sending the correct CORS headers, so I _think_ this is "only" a request to add the `crossorigin` attribute to the appropriate script tags.

Does that sound right based on what you see with your site? 

Is it only the `toolbar.js` that is affected for you?

**Comment by MathiasWP** [comment]
> Hey @MathiasWP
> 
> I've not used COEP before and just reading up here [developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy#avoiding_coep_blockage_with_cors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy#avoiding_coep_blockage_with_cors)
> 
> > If you enable COEP using require-corp and have a cross origin resource that needs to be loaded, it needs to support CORS and you need to explicitly mark the resource as loadable from another origin to avoid blockage from COEP.
> 
> > `<img src="https://thirdparty.com/img.png" crossorigin />`
> 
> eu.posthog.com should be sending the correct CORS headers, so I _think_ this is "only" a request to add the `crossorigin` attribute to the appropriate script tags.
> 
> Does that sound right based on what you see with your site?
> 
> Is it only the `toolbar.js` that is affected for you?

I agree, i believe adding `crossorigin` will solve this issue! The `toolbar.js` is affected, and i believe other scripts like `recorder-v2.js` are also affected. The response header of the script should have `Cross-Origin-Resource-Policy` set to `same-site`, `same-origin`, or `cross-origin`, which does not seem to be have set.

**Comment by MathiasWP** [comment]
What's the status on this issue?

**Comment by annschulte** [comment]
Any updated here?

**Comment by robbie-c** [comment]
We now set `crossorigin="anonymous"` on the snippet and lazily loaded scripts. @MathiasWP did this solve the issue for you?

**Comment by MathiasWP** [comment]
> We now set `crossorigin="anonymous"` on the snippet and lazily loaded scripts. @MathiasWP did this solve the issue for you?

I will check! Thanks
