### ISSUE TITLE
When I clear the browser cookie and localstorage and get distinct_id again, how can I distinct_id still be the same

### ISSUE THREAD

**Issue by npm-ued** [PostHog/posthog-js#987]
When I clear the browser cookie and localstorage and get distinct_id again, how can I distinct_id still be the same. By default, it is stored in a cookie. Is the distinct_id set by the server?

**Comment by pauldambra** [comment]
Hey @npm-ued can you share a little more about what version of posthog-js you're using, how you're configuring it, where you call identify/reset (if you do), and steps to reproduce
