### ISSUE TITLE
List PRs in each release in Github

### ISSUE THREAD

**Issue by MisterJimson** [PostHog/posthog-js#992]
On the Releases page there is no information about what changed in each release: https://github.com/PostHog/posthog-js/releases

It would be nice if each release listed all the PRs/commits within the release with links to them.

Examples
- https://github.com/vercel/next.js/releases
- https://github.com/shadcn-ui/ui/releases
- https://github.com/anoma/namada/releases

**Comment by pauldambra** [comment]
that was trickier than it should have been 🙈 

we now write the last entry from the CHANGELOG.md file to the release when it is created

<img width="695" alt="Screenshot 2024-02-11 at 10 22 10" src="https://github.com/PostHog/posthog-js/assets/984817/f96bd621-72c2-4214-a15a-4c69ca9806f1">

**Comment by MisterJimson** [comment]
Thank you!
